fossil = { -- get kabuto and aerodactyl
	{'w',1},
	{'s',5}, -- fly to blaine
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyDown',9},
	{'a',5},
	{'w',480}, -- on cinnabar
	{'walkLeft',7},
	{'walkUp',4},
	{'w',180},
	{'walkUp',2},
	{'walkRight',22},
	{'walkUp',3},
	{'w',180},
	{'walkRight',4},
	{'walkUp',6},
	{'walkRight',1}, -- talk to this fossil dude but hes a wanderer
	{'mashA',300}, -- just talk talk talk
	{'mashB',10},
	{'walkDown',6},
	{'walkLeft',4},
	{'walkDown',1},
	{'w',180},
	{'walkUp',2},
	{'w',180},
	{'walkRight',4},
	{'walkUp',6},
	{'walkRight',1}, -- now talk to him for a long time. we need to so we can get kabuto and give amber
	{'mashA',500},
	{'walkDown',6},
	{'walkLeft',4},
	{'walkDown',1},
	{'w',180},
	{'walkUp',2},
	{'w',180},
	{'walkRight',4},
	{'walkUp',6},
	{'walkRight',1}, -- now talk to him for a long time. we get aero
	{'mashA',300},
	{'walkDown',6},
	{'walkLeft',4},
	{'walkDown',1},
	{'w',180},
	{'walkLeft',22},
	{'walkDown',5},
	{'w',180}, -- outside fossil world
}
