preLeague = {

	{'w',5},
    {'w', 90},
    {'s', 15},
    {'w', 30},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'walkDown', 1},
    {'a', 15},
    {'walkUp', 2},
    {'a', 15},
    {'w', 90},
    {'press_b', 6},

    {'walkLeft', 6}, -- go to route 22
    {'walkUp', 10},
    --mapChange
    {'walkLeft', 27},
    {'walkDown', 7},
    {'walkLeft', 8},
    {'w', 30},
    {'s', 15},
    {'w', 30},
    {'walkDown', 1},
    {'press_b', 2},

    {'s', 15},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'a', 15},
    {'press_b', 5},

    {'walkUp', 10},
    {'walkLeft', 5},
    {'w', 180},
    {'press_b', 6}, -- fight rival
    {'w', 400},
    {'b', 60},
    {'w', 540},
    {'use_move', 1}, -- OHKO pidgeot
    {'a', 15},
    {'walkRight', 1},
    {'use_move', 1}, -- bite rhyhorn
    {'a', 15},
    {'walkLeft', 1},
    {'use_move', 1}, -- thunderbolt growlithe
    {'w', 540},
    {'a', 15},
    {'walkRight', 1},
    {'use_move', 2}, -- bite exeggcute & alakazam
    {'a', 15},
    {'walkLeft', 1},
    {'use_move', 1}, -- thunderbolt blastoise
    {'press_b', 6}, -- finish rival fight
    {'walkLeft', 18},
    {'walkDown', 4},
    {'w', 30},
    {'walkDown', 5},
    {'walkLeft', 12},
    {'walkUp', 5},
    {'walkRight', 7},
    {'walkUp', 4},
    {'walkLeft', 3},
    {'walkUp', 3},
    {'w', 180},

    {'walkUp', 8},
    {'w', 90},
    {'press_b', 2},
    {'walkUp', 1},
    {'w', 180},
    {'walkUp', 2},
    {'walkRight', 7},
    {'walkUp', 3},
    {'press_b', 8},

    {'walkUp', 6},
    {'walkLeft', 8},
    {'walkUp', 4},
    {'press_b', 8},
    {'walkUp', 5},
    {'w', 120}, -- repel runs out
    {'b', 13},
    {'w', 90},
    {'walkUp', 3},
    {'walkRight', 4},
    {'walkUp', 9},
    {'walkRight', 4},
    {'walkUp', 2},
    {'press_b', 8},
    {'walkUp', 5}, -- approach water
    {'w', 30},

    {'s', 15},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'a', 15},
    {'press_b', 5},

    {'w', 30},
    {'a', 18},
    {'w', 87},
    {'a', 22},
    {'w', 113},
    {'b', 21},
    {'w', 240}, -- get on snok
    {'walkUp', 5}, -- approach next guard
    {'press_b', 8},
    {'walkUp', 7},
    {'walkRight', 2},
    {'walkUp', 11},
    {'walkLeft', 7},
    {'walkUp', 2},
    {'press_b', 8},
    {'walkUp', 9},
    {'walkRight', 4},
    {'walkUp', 8},
    {'w', 90}, -- land on the land
    {'walkUp', 4},
    {'walkRight', 3},
    {'walkUp', 14},
    {'press_b', 8},
    {'walkUp', 12},
    {'walkLeft', 4},
    {'walkUp', 6},
    {'walkLeft', 6},
    {'walkUp', 10},
    {'press_b', 8},
    {'walkUp', 3},
    {'w', 90}, -- repel runs out
    {'b', 60},
    {'walkUp', 5},
    {'w', 540}, -- enter vroad
    -- victory-1
    {'s', 15},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'a', 15},
    {'press_b', 5},
    {'w', 30},
    {'walkUp', 1},
    {'walkLeft', 6},
    {'walkUp', 3},
    {'walkRight', 2},
    {'walkDown', 1},
    {'w', 54},
    {'a', 9}, -- push boulder
    {'w', 99},
    {'a', 18},
    {'w', 74},
    {'a', 18},
    {'w', 208},
    {'b', 19},
    {'w', 59},
    {'b', 24},
    {'w', 90},
    {'walkDown', 1}, -- kick it down 1
    {'w', 70},
    {'walkLeft', 2},
    {'walkDown', 3},
    {'kickR', 5},
    {'w', 70},
    {'walkDown', 2},
    {'walkRight', 3},
    {'walkUp', 2},
    {'w', 70},
    {'walkUp', 2},
    {'w', 70},
    {'walkLeft', 2},
    {'walkUp', 3},
    {'kickR', 7},
    {'walkDown', 2},
    {'walkRight', 3},
    {'walkUp', 2},
    {'w', 70},
    {'walkUp', 2},
    {'w', 70},
    {'walkLeft', 3},
    {'walkUp', 3},
    {'walkRight', 3},
    {'w', 70},
    {'walkUp', 2},
    {'walkRight', 3},
    {'walkDown', 2},
    {'w', 70},
    {'walkLeft', 3},
    {'walkDown', 2},
    {'walkLeft', 2},
    {'walkDown', 3},
    {'walkLeft', 7},
    {'walkDown', 3},
    {'walkLeft', 5},
    {'walkUp', 5},
    {'walkRight', 9},
    {'walkUp', 11},

    -- construction 
    {'walkRight', 4},
    {'walkDown', 6},
    {'walkRight', 4},
    {'walkUp', 7},
    {'walkLeft', 3},
    {'w', 90},
    {'b', 30},
    {'s', 15},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'a', 15},
    {'press_b', 5},
    {'walkLeft', 2},
    {'walkUp', 2},
    {'kickL', 2},
    {'walkLeft', 1},
    {'walkDown', 2},
    {'walkLeft', 2},
    {'kickU', 1},
    {'walkUp', 1},
    {'walkLeft', 2},
    {'w', 30},
    {'a', 14},
    {'w', 120},
    {'press_b', 2},
	{'walkRight', 8},
	{'walkDown', 2},
	{'walkRight', 2},
	{'walkDown', 7},
	{'walkLeft', 4},
	{'walkUp', 6},
	{'walkLeft', 9},
	{'walkDown', 6},
	{'walkLeft', 6},
	{'walkUp', 2},
	{'walkLeft', 2},
	{'walkUp', 8},
	{'walkDown', 8},
	{'walkUp', 8},
	{'walkDown', 8},
	{'walkUp', 8},
	{'walkDown', 8}, -- 6 steps left
	{'walkUp', 5}, 
	{'walkDown', 3},
    {'w', 90},
    {'b', 60},
    {'s', 15},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'a', 15},
    {'press_b', 5},
    {'walkUp', 1},
    {'w', 30},
    {'walkUp', 5}, -- go to ladder
    {'walkLeft', 2}, -- up ladder
    --mapChange
    {'w', 180},
    {'walkDown', 2},
    {'walkRight', 6},
    {'walkDown', 6},
    {'walkRight', 2},
    {'walkDown', 3},
    {'walkLeft', 1},
    {'w', 90},
    {'a', 18},
    {'w', 80},
    {'a', 22},
    {'w', 79},
    {'a', 18},
    {'w', 274},
    {'b', 21},
    {'w', 76},
    {'b', 18},
    {'w', 30},
    {'kickL', 2},
    {'walkUp', 2},
    {'walkLeft', 3},
    {'walkDown', 1},
    {'kickD', 2},
    {'walkRight', 2},
    {'walkDown', 3},
    {'walkLeft', 1},
    {'kickL', 2},
    {'w', 30},
    {'walkRight', 2},
    {'walkUp', 3},
    {'walkRight', 4},
    {'walkUp', 4},
    {'walkRight', 2},
    {'walkUp', 4},
    {'walkUp', 1},
    {'walkRight', 14},
    {'walkDown', 7},
    {'walkRight', 2},
    {'walkDown', 4},
    {'walkRight', 19},
    {'walkUp', 6},
    {'walkLeft', 8},
    {'walkUp', 6},
    {'w', 180},
    {'walkUp', 1},
    {'w', 90},
    {'b', 15},
    {'s', 15},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'a', 15},
    {'press_b', 5},
    {'w', 30},
    {'walkLeft', 3},
    {'walkUp', 3},
    {'w', 60},
    {'a', 28}, -- use strength
    {'w', 67},
    {'a', 25},
    {'w', 64},
    {'a', 22},
    {'w', 189},
    {'b', 33},
    {'w', 44},
    {'b', 41},
    {'kickU', 2},
    {'walkRight', 2},
    {'walkUp', 3},
    {'walkLeft', 1},
    {'kickL', 22},
    {'walkUp', 2},
    {'walkLeft', 3},
    {'walkDown', 1},
    {'kickD', 1},
    {'walkRight', 2},
    {'walkDown', 3},
    {'walkLeft', 1},
    {'kickL', 4},
    {'walkLeft', 1},
    {'walkUp', 2},
    {'walkLeft', 2},
    {'walkDown', 1},
    {'kickD', 3},
    {'walkLeft', 2},
    {'walkDown', 3},
    {'kickR', 1},
    {'w', 60},
    {'walkRight', 1},
    {'walkUp', 4},
    {'walkRight', 7},
    {'walkUp', 2},
    {'walkRight', 19},
    {'walkDown', 6},
    {'walkLeft', 6},
    {'walkUp', 3},
    {'walkLeft', 10},
    {'walkDown', 5},
    {'w', 90},
    {'b', 15},
    {'s', 15},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'a', 15},
    {'press_b', 5},
    {'w', 30},
    {'walkDown', 3},
    {'walkLeft', 7},
    {'walkUp', 3},
    {'walkLeft', 7},
    {'walkDown', 4},
    {'walkRight', 4},
    {'walkDown', 2},
    {'walkRight', 11},
    {'walkDown', 3},
    {'walkDown', 2},
    {'walkRight', 16},
    {'walkUp', 2},
    {'walkRight', 2}, -- rock goes down hole
    {'w', 70},
    {'walkRight', 2}, -- follow rock
    {'w', 240},
    {'walkLeft', 1},
    {'w', 30},
    {'a', 16}, -- use strength
    {'w', 92},
    {'a', 21},
    {'w', 123},
    {'a', 16},
    {'w', 184},
    {'b', 21},
    {'w', 79},
    {'b', 21},
    {'kickL', 19},
    {'walkRight', 16},
    {'walkUp', 3},
    {'walkRight', 6},
    --mapChange
    {'w', 180},
    {'walkRight', 1},
    {'walkUp', 6},
    {'w', 90},
    {'b', 15},
    {'s', 15},
    {'a', 15},
    {'w', 60},
    {'a', 15},
    {'a', 15},
    {'press_b', 5},
    {'walkUp', 3},
    {'walkLeft', 4},
    {'walkDown', 2}, -- down ladder
    {'w', 180},
    {'walkDown', 2},
    {'walkRight', 4},
    {'walkRight', 7},
    {'walkDown', 4},
    --mapChange
    {'w', 240}, -- out of victory road
    -- victory-2


    {'w', 30},
    {'s', 15}, -- teach jolteon shadow ball
    {'w', 77},
    {'a', 23},
    {'w', 116},
    {'walkRight', 1},
    {'w', 187},
    {'a', 28},
    {'w', 71},
    {'a', 22},
    {'w', 80},
    {'walkDown', 7},
    {'a', 15},
    {'a', 15},
    {'w', 90},
    {'a', 15},
    {'w', 120},
    {'b', 16},
    {'w', 120},
    {'b', 17},
    {'w', 165},
    {'a', 16},
    {'w', 111},
    {'b', 24},
    {'w', 400},
    {'walkDown', 1},
    {'w', 26},
    {'walkDown', 1},
    {'w', 156},
    {'a', 20},
    {'w', 291},
    {'b', 20},
    {'w', 124},
    {'b', 22},
    {'w', 124},
    {'b', 19},
    {'w', 127},
    {'b', 15},
    {'w', 199},
    {'b', 19}, 
    {'press_b', 5}, -- done
    {'walkRight', 4},
    {'walkUp', 11},
    {'walkLeft', 8},
    {'walkUp', 15},
    {'walkRight', 2},
    {'walkUp', 4},
    {'walkLeft', 5},
    --mapChange
    {'walkUp', 19}, -- into league
    {'w', 180},
    {'walkRight', 3},
    {'walkUp', 5},
    {'w', 30},
    {'pokecenter_heal',1},
    --mapChange
    {'w', 180},
}
