require("macros")

-- through the second rival battle
require("part1.intro")
require("part1.littleroot")
require("part1.route29")
require("part1.route29_2")
require("part1.route30")
require("part1.rival")
require("part1.firstBattles")
require("part1.violet")
require("part1.wadeCycles")
require("part1.gym1")
require("part1.route32")
require("part1.unioncave")
require("part1.well")
require("part1.gym2")
require("part1.backtrack1")
require("part1.hatch")
require("part1.rival2")

-- through to the fourth gym
require("part2.ilex")
require("part2.route34")
require("part2.goldenrod1")
require("part2.abra")
require("part2.daycare1")
require("part2.evolveAbra")
require("part2.daycare2")
require("part2.gym3")
require("part2.route35")
require("part2.route37")
require("part2.burning")
require("part2.gym4")

-- through to Pryce
require("part3.kimono")
require("part3.route38")
require("part3.lighthouse")
require("part3.route40")
require("part3.gym56")
require("part3.route42")
require("part3.lakeofrage")
require("part3.hideout")
require("part3.gym7")

-- through to league 
require("part4.radiotower1")
require("part4.underground")
require("part4.radiotower2")
require("part4.route44")
require("part4.gym8")
require("part4.den")
require("part4.suicune")
require("part4.candy")
require("part4.route45")
require("part4.route27")
require("part4.victoryroad")
require("part4.league")

require("part5.toKanto")
require("part5.vermillion")
require("part5.celadon")
require("part5.powerplant")
require("part5.lavender_pewter")
require("part5.cinnabar")
require("part5.fuschia_saffron")
require("part5.viridian")
require("part5.finale")
