rival = {
	{"w",60},
	{"talk",7},
	{"w",600},
	{"talk",150}, -- mash A for rival battle
	{"w",30},
	{"walkUp",2},
	{"walkRight",15},
	{"walkDown",5},
	{"walkRight",7},
	{"walkDown",2},
	{"walkRight",2},
	{"walkDown",2},
	{"w",60},
	{"walkRight",18},
	{"walkUp",4},
	{"walkRight",9},
	{"walkDown",2},
	{"walkRight",4},
	{"walkUp",4},
	{"walkRight",2},
	{"w",60},
	{"walkRight",21},
	{"walkUp",6},
	{"walkRight",2},
	{"walkUp",2}, -- in the lab now
	{"w",120},
	{"walkUp",6},
	{"w",180},
	{"talk",8},
	{"w",120}, -- name rival
	{"d",5},
	{"w",30},
	{"r",5},
	{"w",30},
	{"a",5},
	{"w",30},
	{"u",5},
	{"w",30},
	{"r",5},
	{"w",30},
	{"r",5},
	{"w",30},
	{"r",5},
	{"w",30},
	{"a",5},
	{"w",30},
	{"d",5},
	{"w",30},
	{"d",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"a",5},
	{"w",30},
	{"u",5},
	{"w",30},
	{"u",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"a",5},
	{"w",30},
	{"d",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"l",5},
	{"w",30},
	{"a",5},
	{"w",30},
	{"s",5},
	{"w",30},
	{"a",30},
	{"w",300}, -- done naming
	{"talk",2},
	{"w",420},
    {"walkRight",1},
    {"walkUp",1},
    {"talk",6}, -- elm jump back
    {"w",60},
    {"talk",22}, -- done talking to this big talker
    {"w",30},
    {"walkDown",6},
    {"w",180}, -- another big talker!
    {"talk",2},
    {"w",480},
    {"talk",6},
    {"w",300},
    {"walkDown",4},
    {"w",300}, -- out of lab
    {"walkDown",2},
    {"walkLeft",5},
    {"walkDown",3},
    {"walkLeft",10},
    {"w",480}, -- another big talker here to teach me about cathcing pokemon
    {"talk",3},
    {"d",5}, -- please dont teach me
    {"w",30},
    {"talk",4},
    {"w",480}, -- alright let's get going
    {"walkLeft",6},
    {"walkDown",2} -- Then we do Route 29 again
}

