misty = { -- just finished daycare training magikarp. 
	-- when martsnack wrote this part he was "experimenting" with new ways of inputting
	-- they do not work generally. bad! bad! so I rewrote it
	{'w',30},
	{'walkDown',1},
	{'walkRight',1},
	{'w',240},
	{'walkDown',5},
	{'walkLeft',2},
	{'walkDown',1},
	{'w',240},
	{'walkLeft',3},
	{'walkUp',40},
	{'walkRight',11},
	{'walkUp',15},
	{'walkLeft',3},
	{'walkDown',2},
	{'w',60},
	{'walkDown',9},
	{'walkLeft',9},
	{'walkUp',3}, -- mart
	{'w',240},
	{'walkUp',4},
	{'walkLeft',1},
	{'talk',1},
	{'walkDown',1},
	{'talk',1}, -- sell menu
	{'walkDown',1},
	{'talk',1},
	{'walkDown',1},
	{'talk',3}, -- sold my nuggets
	{'mashB',8},
	{'walkDown',6},
	{'w',240}, -- now back to daycare
	{'walkLeft',23},
	{'walkUp',10},
	{'walkRight',2},
	{'walkUp',9},
	{'walkRight',23},
	{'walkUp',1},
	{'w',240},
	{'walkLeft',2},
	{'walkUp',6},
	{'walkRight',3},
	{'walkUp',2},
	{'w',240},
	{'walkUp',1},
	{'walkRight',7},
	{'walkDown',13},
	{'walkRight',3},
	{'walkDown',16},
	{'walkLeft',13},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6}, -- now repel
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',90},
	{'walkUp',1},
	{'talk',3},
	{'mashB',8},
	{'walkDown',1},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',5},
	{'walkUp',1},
	{'w',240},
	{'walkUp',2},
	{'talk',7},
	{'walkDown',4},
	{'w',240},
	{'walkDown',1},
	{'w',60}, -- over to the gym
	{'walkRight',7},
	{'walkUp',36},
	{'walkRight',11},
	{'walkUp',15},
	{'walkLeft',3},
	{'walkDown',2},
	{'w',60},
	{'walkDown',2},
	{'walkLeft',3}, -- repel wears off
	{'mashB',3},
	{'walkLeft',4},
	{'walkUp',3},
	{'w',240}, -- in the gym
	{'walkRight',2},
	{'walkUp',6},
	{'walkLeft',6},
	{'walkUp',4},
	{'walkRight',9},
	{'walkUp',4},
	{'walkLeft',5},
	{'w',120},
	{'mashB',30},
	{'a',5},
	{'a',5},
	{'mashB',30},
	{'walkUp',1},
	{'a',5},
	{'mashB',40},
	{'a',5},
	{'r',30},
	{'a',5},
	{'mashB',30},
	{'a',5},
	{'a',5},
	{'mashB',50}, -- bye misty!
	{'walkRight',5},
	{'walkDown',4},
	{'walkLeft',9},
	{'walkDown',4},
	{'walkRight',6},
	{'walkDown',4},
	{'walkLeft',2},
	{'walkDown',4},
	{'w',240}, -- outside the gym
	{'w',1},
}
