burning = {
	{'w',30}, -- go to the tower 
	{'walkLeft',8},
	{'walkUp',17},
	{'walkLeft',14},
	{'walkUp', 3},
	{'walkRight',4},
	{'walkUp', 4},
	{'walkLeft',2},
	{'walkDown',1},
	{'resetMenu',1}, -- reset menu
	{'walkUp',3},
	{'w',360}, -- in tower. hi eusine!
	{'mashB',15},
	{'s',5}, -- use repel
	{'w',60},
	{'walkUp',5},
	{'a',5},
	{'w',60},
	{'walkDown',9},
	{'talk',2},
	{'mashB',8},
	{'s',5}, -- now teach croc dig
	{'w',60},
	{'a',5},
	{'w',60},
	{'walkLeft',1},
	{'walkUp',1},
	{'talk',12},
	{'walkDown',1},
	{'talk',1},
	{'w',60},
	{'mashB',15},
	{'s',5},
	{'w',60}, -- now switch kad to 1st
	{'walkUp',1},
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',30},
	{'walkDown',4},
	{'a',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',60},
	{'mashB',5}, -- finally ready to go fight rival
	{'walkLeft',6},
	{'walkUp',5},
	{'walkLeft',2},
	{'walkUp',8},
	{'walkRight',3},
	{'walkUp',4},
	{'walkRight',5},
	{'walkDown',5},
	{'walkRight',4},
	{'walkDown',5},
	{'walkLeft',2},
	{'w',300},
	{'mashB',50},
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',400}, -- super eff text, MAYBE crit text
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',30}, -- fast one in case of crit
	{'a',5},
	{'w',240},
	{'talk',3},
	{'walkDown',1},
	{'talk',2},
	{'w',600},
	{'a',5},
	{'w',30}, -- dig time
	{'walkDown',1},
	{'a',5},
	{'w',60},
	{'talk',1}, -- dig text
	{'w',240}, -- mag attempts to do somethin
	{'talk',1}, -- miss text
	{'w',400}, -- super eff text, MAYBE crit text
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',30}, -- fast one in case of crit
	{'a',5},
	{'w',240},
	{'talk',3},
	{'walkUp',1},
	{'talk',2},
	{'w',600}, -- Bayleef in, Kad in
	{'a',5}, -- use ice punch. 
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'mashB',40},
	{'a',5}, -- use psybeam on zubat. 
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',60}, -- im in the hole lol. Rival down!
	{'walkUp',4}, -- long cutscene here. ~15 seconds
	{'w',1200},
	{'walkDown',5},
	{'talk',16},
	{'w',300}, -- by eusine! what a day we've had together
	{'walkDown',3},
	{'walkLeft',4},
	{'walkDown',2},
	{'w',120},
	{'walkRight',3},
	{'walkDown',2},
	{'w',120}, -- out of the tower. walk to Morty's gym
	{'walkDown',1},
	{'walkRight',2},
	{'walkDown',4},
	{'walkLeft',4},
	{'walkDown',19},
	{'walkRight',4},
	{'walkUp',2},
	{'w',120}, -- in Morty's gym!
}
