goldenrod1 = { -- grab bike, fight trainers in the underground
	{"w",30},
	{"walkRight",4},
	{"walkUp",7},
	{"walkRight",4},
	{"walkUp",6},
	{"walkRight",8},
	{"walkDown",7},
	{"walkRight",5},
	{"walkDown",8},
	{"walkLeft",4},
	{"walkUp",2},
	{"w",120}, -- in cycle shop
	{"walkRight",4},
	{"walkUp",6},
	{"walkRight",1},
	{"talk",8},
	{"w",120},
	{"talk",4}, -- got the bike. cool!
	{"walkDown",6},
	{"walkLeft",3},
	{"walkDown",2},
	{"w",120},
	{"walkRight",4},
	{"walkUp",9},
	{"walkLeft",5},
	{"walkUp",7},
	{"walkLeft",8},
	{"walkUp",9},
	{"walkLeft",13},
	{"walkUp",4},
	{"w",120},
	{"walkUp",4},
	{"walkRight",2},
	{"w", 120}, -- we underground
	{"walkDown",5},
	{"w",180},
	{"talk",3},
	{"w",180},
	{"mashB",20},
	{"a",5},
	{"w",30},
	{"walkUp",1},
	{"a",5},
	{"w",30},
	{"mashB",30},
	{"talk",2},
	{"mashB",30},
	{"walkDown",2},
	{"walkRight",4},
	{"w",180},
	{"talk",4},
	{"w",180},
	{"mashB",30}, -- use water gun on magnemite
	{"talk",2},
	{"mashB",30}, -- use water gun on magnemite
	{"talk",2},
	{"mashB",30}, -- use water gun on magnemite
	{"talk",2},
	{"mashB",30},
	{"talk",1},
	{"walkUp",1}, -- headbutt on voltorb
	{"talk",1},
	{"mashB",30},
	{"walkLeft",2},
	{"walkDown",19},
	{"walkRight",2},
	{"talk",8}, -- the lickitung here is too strong to kill right now
}
