gymCycle = {
	{'w',1},
    {'walkUp', 2},
    {'w', 160},
    {'walkUp', 4},
    {'walkLeft', 6},
    {'walkUp', 2},
    {'walkRight', 1}, -- in position for verm loop
    {'a', 15}, -- check can 1
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkUp', 3},
    {'walkRight', 1},
    {'a', 15}, -- check can 6
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkUp', 3},
    {'walkRight', 1},
    {'a', 15}, -- check can 11
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkUp', 2},
    {'walkRight', 5},
    {'walkDown', 2},
    {'walkLeft', 1},
    {'a', 15}, -- check can 12
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkDown', 3},
    {'walkLeft', 1},
    {'a', 15}, -- check can 7
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkDown', 3},
    {'walkLeft', 1},
    {'a', 15}, -- check can 2
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkDown', 2}, 
    {'walkRight', 3},
    {'walkUp', 2},
    {'walkLeft', 1},
    {'a', 15}, -- check can 3
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkRight', 1},
    {'a', 15}, -- check can 4
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkUp', 3},
    {'walkRight', 1},
    {'a', 15}, -- check can 9
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkLeft', 1},
    {'a', 15}, -- check can 8
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkUp', 3},
    {'walkLeft', 1},
    {'a', 15}, -- check can 13
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkRight', 1},
    {'a', 15}, -- check can 14
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkUp', 2},
    {'walkRight', 5},
    {'walkDown', 2},
    {'walkLeft', 1},
    {'a', 15}, -- check can 15
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkDown', 3},
    {'walkLeft', 1},
    {'a', 15}, -- check can 10
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkDown', 3},
    {'walkLeft', 1},
    {'a', 15}, -- check can 5
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkDown', 2},
    {'walkLeft', 4},
    {'walkUp', 1},
    {'a', 15}, -- check last can
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'b', 30},
    {'walkLeft', 3},
    {'walkDown', 6},
    {'w', 120},

}
