forest1 = {
	{'w',1},
	{'w', 300}, -- enter viridian forest
    {'walkUp', 3}, -- start walk to anthony
    {'walkRight', 10},
    {'walkDown', 2},
    {'walkRight', 5},
    {'walkUp', 15},
    {'walkLeft', 2},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkRight', 1},
    {"grass_cycle", 1},
    {'walkRight', 1},
    {'walkRight', 6},
    {'walkUp',17},
    {'walkLeft', 8},
    {'walkUp', 10},
    {'walkLeft', 6},
    {"grass_cycle", 1},
    {'walkLeft', 1},
    {"grass_cycle", 1},
    {'walkLeft', 1},
    {"grass_cycle", 1},
    {'walkLeft', 1},
    {"grass_cycle", 1},
    {'walkLeft', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 2},
    {'walkLeft', 10},
    {'walkUp', 3}, -- exit grass
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {'walkUp', 6},
    {'walkLeft', 8},
    {'a', 15}, -- fight bug catcher anthony //video breakpoint
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 240},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 450},
    {'a', 15}, -- scratch 1
    {'a', 15},
    {'w', 300},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'a', 15}, -- scratch 2
    {'a', 15},
    {'w', 300},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'a', 15}, -- scratch 3 (potential KO on crits)
    {'a', 15},
    {'w', 300},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 120},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 120},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'a', 15}, -- scratch/ember 4
    {'s', 20},
    {'d', 10},
    {'s', 20},
    {'a', 15},
    {'w', 300},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 120},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 120},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'attack_down_ember', 17}, -- end fight / video breakpoint
    {'walkDown', 6}, -- fighting rick / video breakpoint
    {'walkRight', 7},
    {'walkDown', 3},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {"grass_cycle", 1},
    {'walkDown', 1},
    {'walkDown', 1},
    {'walkRight', 10},
    {'walkUp', 2},
    {'walkUp', 1},
    {'grass_cycle', 1},
    {'walkUp', 1},
    {'grass_cycle', 1},
    {'walkUp', 1},
    {'grass_cycle', 1},
    {'walkRight', 1},
    {'grass_cycle', 1},
    {'walkRight', 1},
    {'grass_cycle', 1},
    {'walkRight', 1},
    {'grass_cycle', 1},
    {'walkRight', 1},
    {'grass_cycle', 1},
    {'walkRight', 1},
    {'grass_cycle', 1},
    {'walkRight', 1}, -- exit grass
    {'walkRight', 5},
    {'walkDown', 9},
    {'walkRight', 7},
    {'walkDown', 17},
    {'walkLeft', 3},
    {'walkDown', 4},
    {'w', 120}, -- start battle with rick (430xp/500xp)
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 420},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 240},
    {'a', 15},
    {'d', 10},
    {'a', 15}, -- use ember, will faint caterpie
    {'w', 480}, -- wait for battle sequence
    {'b', 60}, -- skip through text 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, -- go through level up text (lvl 6 charm)
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'w', 480}, -- wait for caterpie to be sent out
    {'a', 15},
    {'a', 15}, -- use ember, will faint second caterpie
    {'w', 480}, -- wait for battle sequence
    {'b', 60}, 
    {'b', 60}, -- spam through end of battle text (lvl 5 charm gets to 10 here)
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'b', 60}, 
    {'w', 300}, -- rick defeated // video breakpoint
    {'walkUp', 4}, -- go to doug
    {'walkRight', 3},
    {'walkUp', 17},
    {'walkLeft', 4},
    {'walkDown', 4}, -- doug spots us
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 600},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 240}, -- start fight
    {'a', 15},
    {'d', 10},
    {'a', 15},
    {'w', 480},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'a', 15},
    {'u', 10},
    {'r', 10},
    {'a', 15},
    {'w', 480},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'use_growl', 25}, -- lose battle, end up in center / video breakpoint
	{'w',1},
}
