intro = {
	{'w',5},
	{'w', 350}, -- start the rom
    {'a', 15},
    {'w', 350},
    {'s', 15},
	{'w', 200},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'w', 180},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'w', 540},
    {'a', 60},
    {'a', 5},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 80},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'w', 60},
    {'a', 60},
    {'w', 120},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'walkDown', 3},
    {'a',5},
    {'w', 90},
    {'a', 60},
    {'w', 120},
    {'walkDown',1}, -- name character
    {'walkDown',1},
    {'walkLeft',1},
    {'walkLeft',1},
    {'walkLeft',1},
    {'a',5},
    {'walkLeft',1},
    {'walkLeft',1},
    {'walkLeft',1},
    {'walkLeft',1},
    {'a',5},
    {'walkLeft',1},
    {'walkDown',1},
    {'a',5},
    {'walkUp',1},
    {'walkRight',1},
    {'walkRight',1},
    {'a',5},
    {'s',5},
    {'a',5},
    {'w', 240},
    {'a', 5},
    {'w', 300},
    {'a', 5}, 
    {'a', 60},
    {'a', 60},
    {'a', 60}, -- name grandson
    {'w', 30},
    {'walkRight',1},
    {'walkRight',1},
    {'walkRight',1},
    {'a',5},
    {'walkLeft',1},
    {'walkLeft',1},
    {'walkLeft',1},
    {'a',5},
    {'walkDown',1},
    {'walkDown',1},
    {'walkDown',1},
    {'walkRight',1},
    {'walkRight',1},
    {'a',5},
    {'walkUp',1},
    {'walkUp',1},
    {'walkUp',1},
    {'walkRight',1},
    {'walkRight',1},
    {'a',5},
    {'s', 30},
    {'a', 15},
    {'w', 180},
    {'a', 15},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'w', 300}, -- enter game
    {'s', 60}, -- change battle scene
    {'walkDown', 3},
    {'a',5},
    {'w', 180},
    {'walkRight',1},
    {'walkDown', 1},
    {'walkRight',1},
    {'a',5},
    {'w', 120},
    {'s',5},
    {'w', 180},
    {'walkLeft', 4},
    {'walkUp', 5},
    {'walkLeft', 3},
    {'walkUp', 1},
    {'w', 30},
    {'a', 8},
    {'w', 30},
    {'press_a', 7},
    {'press_b', 4},
    {'w', 30},
    {'walkRight', 7},
    {'walkDown', 3},
    {'walkRight', 4},
    {'walkUp', 3},
    {'walkLeft', 2},
    {'w',80},
    {'walkDown',6},
    {'walkLeft',7},
    {'walkDown',3},
    {'w',100},
    {'walkRight',6},
    {'walkUp',7},
    {'walkRight',2},
    {'walkUp',2},
    {'w',540},
    {'a',60},
    {'a',60},
    {'a',60},
    {'a',1},
    {'w',720},
    {'a',60},
    {'a',3},
    {'w',120},
    {'a',20},
    {'a',80},
    {'a',80},
    {'a',80},
    {'a',80},
    {'a',80},
    {'a',80},
    {'w',60},
    {'b',80},
    {'b',80},
    {'b',80},
    {'b',80},
    {'b',60},
    {'b',60},
    {'b',60},
    {'b',60},
    {'b',60},
    {'walkRight',2},
    {'walkUp',2},
    {'walkRight',4},
    {'walkDown',2},
    -- RECORD: First Fight Start
    {'a',3},
    {'w',20},
    {'a',60},
    {'a',60},
    {'w',20},
    {'a',5},
    {'a',60},
    {'a',5},
    {'a',80},
    {'a',80},
    {'w',360},
    {'a',5},
    {'w',60},
    {'walkRight',1}, -- naming charmander
    {'walkRight',1},
    {'walkRight',1},
    {'a',5},
    {'walkRight',1},
    {'a',5},
    {'walkLeft',1},
    {'walkLeft',1},
    {'walkLeft',1},
    {'walkLeft',1},
    {'a',5},
    {'walkDown',1},
    {'walkDown',1},
    {'walkDown',1},
    {'a',5},
    {'walkUp',1},
    {'walkUp',1},
    {'walkRight',1},
    {'a',5},
    {'s',5},
    {'a',5},
    {'w',180},
    {'a',5},
    {'a',60},
    {'a',5},
    {'w',360},
    {'a',5}, -- end
    {'walkLeft',4}, -- fight with rival
    {'walkDown',6},
    {'w',60},
    {'a',60},
    {'a',60},
    {'a',60}, -- enter fight
    {'a',60},
    {'w',500}, -- breakpoint
    {'b', 15},
    {'w', 400},
    {'b', 15},
    {'w', 90},
    {'b', 15},
    {'w', 90},
    {'b', 15},
    {'w', 120},
    {'b', 15},
    {'w', 90},
    {'b', 15},
    {'w', 153},
    {'b', 18},
    {'w', 94},
    {'b', 22},
    {'w', 148},
    {'b', 19},
    {'w', 123},
    {'b', 60},
    {'b', 16}, -- turn 1 
    {'a', 15},
    {'a', 15}, -- use scratch 
    {'w', 180},
    {'press_b', 5},
    {'w', 300}, -- turn 2
    {'a', 15},
    {'a', 15},
    {'w', 540}, -- turn 3
    {'a', 15},
    {'a', 15},
    {'w', 540}, -- turn 4
    {'walkRight', 1},
    {'a', 21},
    {'w', 40},
    {'a', 21},
    {'w', 42},
    {'a', 20},
    {'w', 60},
    {'a', 29},
    {'w', 60},
    {'a', 29},
    {'w', 60},
    {'a', 29},
    {'w', 60},
    {'press_a', 5},
    {'press_b', 5},
    {'w', 300}, -- turn 5
    {'walkLeft', 1},
    {'a', 15},
    {'a', 15},
    {'w', 540}, -- turn 6
    {'a', 15},
    {'a', 15}, -- fight over
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60}, -- end rival fight 
    -- STOP RECORDING
    -- START RECORDING GRASS SECTION
    {'walkLeft',2},
    {'walkDown',6},
    {'w',180},
    {'walkLeft', 5},
    {'walkUp', 12},
    {'walkRight', 2},
    {'walkUp', 2},
    {'b', 15},
    {'b', 60}, -- b spam through text
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 15},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'walkUp',3}, -- walk through grass to viridian from pallet
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1 },
    {'walkLeft', 6},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 2},
    {'walkRight', 10},
    {'walkUp', 3},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkRight', 1},
    {"grass_cycle", 1},
    {'walkRight', 1},
    {'walkUp',3},
    {'walkLeft',9},
    {'walkUp',5},
    {'walkRight',7},
    {'walkUp',3},
    {"grass_cycle", 1},
    {'walkUp',1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkLeft', 1},
    {"grass_cycle", 1},
    {'walkLeft', 1},
    {'walkUp', 4},
    {'walkRight', 2},
    {'walkUp', 2},
    {"grass_cycle", 1},
    {'walkUp',1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1}, -- out of grass and into viridian
    {'walkUp', 2},
    -- END RECORDING
    {'walkLeft', 7}, --  go to mart
    {'walkUp', 16},
    {'walkRight', 10},
    {'walkUp', 14},
    {'walkRight', 8},
    {'walkDown', 5},
    {'walkLeft', 3},
    {'walkUp', 2},
    {'b', 60}, -- pick up parcel
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'walkDown',7}, -- leave mart
    {'w', 120},
    {'walkRight', 3},
    {'walkUp', 5},
    {'walkLeft', 8},
    {'walkDown', 14},
    {'walkLeft', 10},
    {'walkDown', 15},
    {'walkLeft', 5},
    {'walkDown', 18},
    {'walkRight', 14},
    {'walkDown', 9},
    {'walkLeft', 8},
    {'walkDown', 6},
    {'walkDown',1},
    {"grass_cycle", 1},
    {'walkDown',1},
    {"grass_cycle", 1},
    {'walkDown',1},
    {"grass_cycle", 1},
    {'walkDown',1},
    {"grass_cycle", 1},
    {'walkDown',1},
    {"grass_cycle", 1},
    {'walkDown', 15}, -- enter pallet 
    {'walkRight', 5},
    {'walkUp', 2},
    {'w', 120},
    {'walkUp', 8},
    {'a', 15},
    {'a', 15},
    {'b', 60}, -- talk to oak, get dex
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'walkDown', 9}, -- out of lab
    {'w', 150},
    {'walkLeft', 5},
    {'walkUp', 15},
    {'walkRight', 2},
    {'walkUp', 2}, -- up to grass
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1 },
    {'walkLeft', 6},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 2},
    {'walkRight', 10},
    {'walkUp', 3},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkRight', 1},
    {"grass_cycle", 1},
    {'walkRight', 1},
    {'walkUp',3},
    {'walkLeft',9},
    {'walkUp',5},
    {'walkRight',7},
    {'walkUp',3},
    {"grass_cycle", 1},
    {'walkUp',1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkLeft', 1},
    {"grass_cycle", 1},
    {'walkLeft', 1},
    {'walkUp', 4},
    {'walkRight', 2},
    {'walkUp', 2},
    {"grass_cycle", 1},
    {'walkUp',1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1},
    {'walkUp', 1},
    {"grass_cycle", 1}, -- out of grass and into viridian
    {'walkUp', 2},
    {'walkLeft', 5}, -- go to mart
    {'walkUp', 14},
    {'walkLeft', 3},
    {'walkUp', 5},
    {'walkUp', 6},
    {'walkRight', 15},
    {'walkUp', 4},
    {'w', 240},
    {'walkUp', 4},
    {'walkLeft', 1},
    {'a', 15}, -- start shopping
    {'w', 180},
    {'a', 15},
    {'w', 120},
    {'walkDown', 2},
    {'a', 15},
    {'w', 150},
    {'a', 15},
    {'a', 60}, -- buy antidote
    {'a', 60},
    {'w', 180},
    {'a', 15},
    {'w', 60},
    {'walkUp', 1}, -- buy potions
    {'a', 15},
    {'w', 240},
    {'walkDown', 1},
    {'a', 15},
    {'a', 60},
    {'a', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60}, -- exit mart menu
    {'walkDown', 6},
    {'w', 240},
    {'walkLeft', 6},
    {'walkDown', 8},
    {'walkLeft', 6},
    {'walkUp', 2},
    {'w', 240},
    {'walkUp', 4},
    {'a', 15},
    {'a', 60}, -- talk to nurse joy
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'a', 60},
    {'w', 300},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'walkDown', 6},
    {'w', 240},
    {'walkLeft', 5},
    {'walkUp', 20},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'w', 2200}, -- watch old man pokeball
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'b', 60},
    {'walkUp', 20},
    {'walkLeft', 6},
    {'walkUp', 8},
    {'walkRight', 9},
    {'walkUp', 9},
    {'walkLeft', 8},
    {'walkUp', 5},
    {'w', 180},
    {'walkUp', 10},
    {'w', 300}, 
}
