casino = {
	{'w',5},
    {'w', 60}, -- pick up all stray coins
    {'walkLeft', 2},
    {'walkDown', 1},
    {'w', 99},
    {'a', 17},
    {'w', 101},
    {'b', 17},
    {'w', 58},
    {'b', 20},
    {'w', 88},
    {'walkDown', 3},
    {'w', 99},
    {'walkRight', 2},
    {'w', 55},
    {'a', 16},
    {'w', 70},
    {'b', 27},
    {'w', 64},
    {'b', 23},
    {'w', 38},
    {'walkRight', 2},
    {'w', 31},
    {'a', 19},
    {'w', 239},
    {'b', 20},
    {'w', 165},
    {'walkLeft', 2},
    {'w', 57},
    {'walkDown', 7},
    {'w', 50},
    {'walkDown', 1},
    {'w', 42},
    {'a', 16},
    {'w', 93},
    {'b', 21},
    {'w', 112},
    {'b', 23},
    {'w', 51},
    {'walkLeft', 2},
    {'w', 33},
    {'a', 19},
    {'w', 15},
    {'walkLeft', 1},
    {'w', 31},
    {'a', 18},
    {'w', 97},
    {'b', 24},
    {'w', 82},
    {'b', 23},
    {'w', 22},
    {'walkLeft', 5},
    {'w', 25},
    {'a', 24},
    {'w', 56},
    {'walkLeft', 1},
    {'a', 19},
    {'w', 245},
    {'b', 31},
    {'w', 70},
    {'walkLeft', 4},
    {'w', 54},
    {'walkLeft', 1},
    {'w', 41},
    {'walkUp', 1},
    {'w', 44},
    {'a', 16},
    {'w', 115},
    {'b', 17},
    {'w', 99},
    {'b', 14},
    {'w', 24},
    {'walkRight', 2},
    {'walkUp', 4},
    {'w', 40},
    {'a', 19},
    {'w', 241},
    {'b', 23},
    {'w', 44},
    {'walkUp', 5},
    {'w', 77},
    {'walkLeft', 1},
    {'w', 48},
    {'a', 13},
    {'w', 202},
    {'b', 16},
    {'w', 33},
    {'walkRight', 7},
    {'w', 28},
    {'walkDown', 1},
    {'w', 22},
    {'a', 8},
    {'w', 63},
    {'a', 14},
    {'w', 45},
    {'walkLeft', 2},
    {'w', 30},
    {'walkDown', 1},
    {'w', 40},
    {'a', 9},
    {'w', 309},
    {'b', 15},
    {'w', 51},
    {'walkRight', 2},
    {'w', 37},
    {'a', 19},
    {'w', 365},
    {'b', 17}, -- finish picking up coins
    {'w', 60},
    {'w', 60},
    {'walkLeft', 4}, -- go buy coins for thunderbolt
    {'w', 32},
    {'walkUp', 1},
    {'w', 46},
    {'a', 16},
    {'w', 140},
    {'a', 21},
    {'w', 210},
    {'walkDown', 1},
    {'w', 66},
    {'a', 15},
    {'w', 156},
    {'b', 24},
    {'w', 87},
    {'a', 20},
    {'w', 85},
    {'a', 21},
    {'w', 113},
    {'walkDown', 1},
    {'w', 41},
    {'a', 18},
    {'w', 139},
    {'b', 19},
    {'w', 64},
    {'a', 23},
    {'w', 75},
    {'a', 23},
    {'w', 104},
    {'walkDown', 1},
    {'w', 86},
    {'a', 18},
    {'w', 91},
    {'b', 21},
    {'w', 85},
    {'a', 24},
    {'w', 78},
    {'a', 25},
    {'w', 103},
    {'walkDown', 1},
    {'w', 29},
    {'a', 22},
    {'w', 75},
    {'b', 33},
    {'w', 107},
    {'a', 25},
    {'w', 82},
    {'a', 25},
    {'w', 88},
    {'walkDown', 1},
    {'w', 53},
    {'a', 22},
    {'w', 86},
    {'b', 26},
    {'w', 54},
    {'a', 25},
    {'w', 76},
    {'a', 21},
    {'w', 86},
    {'walkDown', 1},
    {'a', 18},
    {'w', 86},
    {'b', 27},
    {'w', 48},
    {'a', 26},
    {'w', 69},
    {'a', 24},
    {'w', 81},
    {'walkDown', 1},
    {'a', 21},
    {'w', 59},
    {'b', 27},
        {'w', 48},
    {'a', 26},
    {'w', 69},
    {'a', 24},
    {'w', 81},
    {'walkDown', 1},
    {'a', 21},
    {'w', 59},
    {'b', 27},
        {'w', 48},
    {'a', 26},
    {'w', 69},
    {'a', 24},
    {'w', 81},
    {'walkDown', 1},
    {'a', 21},
    {'w', 59},
    {'b', 27},
    {'w', 54},
    {'a', 22},
    {'w', 65},
    {'a', 25},
    {'w', 79},
    {'walkDown', 1},
    {'a', 21},
    {'w', 99},
    {'b', 23}, -- done buying coins
    {'w', 120},
    {'w', 219},
    {'walkDown', 2},
    {'w', 27},
    {'walkRight', 4},
    {'w', 24},
    {'walkDown', 10}, -- out of casino
    --mapChange
    {'w', 180},
    {'walkRight', 6},
    {'walkUp', 3}, -- into prize room
    --mapChange
    {'w', 180},
    {'walkUp', 5}, -- get thunderbolt
    {'w', 46},
    {'walkRight', 3},
    {'w', 48},
    {'walkUp', 1},
    {'w', 52},
    {'a', 18},
    {'w', 110},
    {'a', 21},
    {'w', 178},
    {'walkDown', 1},
    {'w', 157},
    {'walkDown', 1},
    {'w', 164},
    {'a', 13},
    {'w', 200},
    {'a', 17},
    {'w', 308},
    {'b', 15},
    {'w', 287},
    {'walkLeft', 3},
    {'w', 86},
    {'walkUp', 1}, -- get abra
    {'w', 72},
    {'a', 15},
    {'w', 155},
    {'a', 13},
    {'w', 240},
    {'a', 16},
    {'w', 174},
    {'a', 13},
    {'w', 233},
    {'b', 23},
    {'w', 90},
    {'walkLeft', 3}, -- go get charcoal
    {'w', 46},
    {'walkUp', 1},
    {'w', 153},
    {'a', 13},
    {'w', 184},
    {'a', 13},
    {'w', 262},
    {'walkDown', 1},
    {'w', 60},
    {'walkDown', 1},
    {'w', 60},
    {'a', 16},
    {'w', 134},
    {'a', 23},
    {'w', 233},
    {'b', 22}, -- charcoal bought
    {'w', 90},
    --rockethide-5
    {'walkRight', 3}, -- out of prize room
    {'w', 40},
    {'walkDown', 6},
    --mapChange
    {'w', 180},
    {'walkDown', 2},
    {'walkRight', 3},
    {'walkUp', 7},
    {'walkLeft', 8},
    {'walkUp', 2},
    {'walkLeft', 5},
    {'walkUp', 5},  -- into mansion
    --mapChange
    {'w', 201},
    {'walkUp', 4}, -- go to old woman
    {'w', 59},
    {'walkLeft', 13},
    {'w', 26},
    {'walkUp', 7},
    {'w', 33},
    {'walkRight', 2},
    {'w', 67},
    {'walkRight', 1},
    {'w', 42},
    {'walkDown', 1},
    {'w', 78},
    {'a', 11}, -- get tea
    {'w', 117},
    {'a', 12},
    {'press_b', 7},
    {'w', 30},
    {'walkLeft', 3}, -- leave mansion
    {'walkDown', 7},
    {'walkRight', 13},
    {'walkDown', 6},
    --mapChange
    {'w', 180},
    {'walkRight', 19}, -- go to pokecenter
    {'walkUp', 2},
    --mapChange
    {'w', 180},
    {'walkUp', 6},
    {'w', 30},
    {'pokecenter_heal', 1},
    {'w', 30},
    {'walkDown', 7},
    {'w', 180},
    {'walkRight', 22},
    {'walkDown', 6},
    {'walkLeft', 3},
    {'walkDown', 4},
    {'walkRight', 10}, -- into guard passway
    --mapChange
    {'w', 180},
    {'walkRight', 6},
    {'w', 30},
    {'press_b', 15}, -- give tea to guy
    {'w', 30},
    {'walkDown', 2},
    {'walkRight', 7},
    {'w', 180}, -- enter saffron
    {'walkRight', 8},
    {'walkUp', 18},
    {'walkRight', 20},
    {'walkUp', 7}, -- into guard passway
    --mapChange
    {'w', 180},
    {'walkUp', 9}, -- exit
    --mapChange
    {'w', 180},
    {'walkUp', 4}, -- go to daycare
    {'walkRight', 6},
    --mapChange
    {'walkUp', 36},
    {'walkLeft', 6},
    {'walkDown', 2},
    {'w', 209},
    {'s', 10}, -- apply repel
    {'w', 126},
    {'walkDown', 1}, -- go to bag (we're on pokemon)
    {'w', 30},
    {'a', 15},
    {'w', 300},
    {'walkLeft', 3},
    {'walkDown', 17},
    {'w', 60},
    {'walkUp', 10},
    {'w', 60},
    {'a', 60}, 
    {'a', 60},
    {'w', 90},
    {'press_b', 6}, -- exit menu
    {'w', 60},
    --mapChange
    {'walkDown', 30},
    {'w', 60},
    {'walkRight', 3},
    {'walkDown', 6},
    {'walkLeft', 4},
    {'walkUp', 2},
    {'w', 180}, -- into daycare
}
