preHideout = {
	{'w',30},
	{'w', 204}, -- leave celadon gym
    {'walkDown', 15},
    --mapChange
    {'w', 256},
    {'walkDown', 4},
    {'walkRight', 9},
    {'walkDown', 2},
    {'walkRight', 5},
    {'walkDown', 2},
    {'walkRight', 18},
    {'walkUp', 2},
    {'w', 60},
    {'a', 12},
    {'w', 56},
    {'a', 22},
    {'w', 54},
    {'a', 21},
    {'w', 57},
    {'a', 19},
    {'w', 197},
    {'walkUp', 3},
    {'walkLeft', 17},
    {'walkUp', 9},
    {'walkLeft', 17},
    {'walkUp', 2},
    {'walkLeft', 2},
    {'walkUp', 10},
    {'walkRight', 37},
    {'walkUp', 4},
    {'walkRight', 6},
    {'walkUp', 2},
    --mapChange
    {'w', 200},
    {'walkUp', 7},
    {'w', 60},
    {'pokecenter_heal', 1},
    {'w', 180},
    {'walkDown', 6},
    --mapChange
    {'w', 244},
    {'walkRight', 4},
    {'walkUp', 6},
    {'walkLeft', 13},
    {'walkLeft', 1},
    {'walkUp', 6},
    {'walkLeft', 9},
    {'walkDown', 4},
    --mapChange
    {'w', 160},
    {'walkRight', 4},
    --mapChange
    {'w', 102},
    {'walkLeft', 4},
    --mapChange
    {'w', 106},
    {'walkRight', 4},
    --mapChange
    {'w', 107},
    {'walkLeft', 2},
    {'w', 24},
    {'walkDown', 4},
    {'w', 21},
    {'walkRight', 4},
    {'w', 26},
    {'walkDown', 9},
    {'w', 39},
    {'walkLeft', 3},
    {'w', 51},
    {'walkLeft', 1},
    {'w', 45},
    {'walkUp', 2},
    --mapChange
    {'w', 142}, -- acquire eevee
    {'walkUp', 1},
    {'w', 26},
    {'walkRight', 3},
    {'w', 61},
    {'walkRight', 1},
    {'w', 30},
    {'walkUp', 3},
    {'w', 39},
    {'a', 21},
    {'w', 62},
    {'a', 45},
    {'w', 41},
    {'walkDown', 2},
    {'walkRight', 2},
    {'a', 15},
    {'walkUp', 2},
    {'walkLeft', 3},
    {'a', 15}, 
    {'w', 60},
    {'walkRight', 4},
    {'walkDown', 3},
    {'a', 15},
    {'walkUp', 3},
    {'walkLeft', 4},
    {'a', 60},
    {'a', 60},
    {'walkRight', 3},
    {'walkDown', 2},
    {'a', 15},
    {'s', 15},
    {'a', 15}, -- named eevee
    {'w', 100},
    {'w', 258}, -- leave building
    {'walkDown', 4},
    {'walkLeft', 4},
    --mapChange
    {'walkDown', 2},
    {'w', 179},
    {'walkRight', 4},
    {'walkUp', 9},
    {'walkLeft', 3},
    {'walkUp', 4},
    {'walkRight', 3},
    --mapChange
    {'w', 215},
    {'walkLeft', 3},
    --mapChange
    {'w', 103},
    {'walkRight', 3},
    --mapChange
    {'w', 100},
    {'walkLeft', 2},
    {'walkUp', 2},
    --mapChange
    {'w', 200},
    {'walkUp', 2},
    {'walkLeft', 26},
    {'walkDown', 1},
    {'w', 135},
    {'a', 9},
    {'w', 89},
    {'a', 18},
    {'w', 42},
    {'a', 21},
    {'w', 217},
    {'walkRight', 35},
    {'w', 71},
    {'walkDown', 5},
    {'w', 33},
    {'walkRight', 13},
    {'w', 25},
    {'walkDown', 8},
    {'w', 36},
	-- here, martsnack had gyarados in the box. I have him in the party
	-- move him to slot three first
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',90},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'b',5},
	{'w',120},
	{'walkDown',1}, -- teach water pulse
    {'a', 13},
    {'w', 166},
    {'walkLeft', 1},
    {'w', 298},
    {'walkRight', 1},
    {'w', 383},
    {'a', 11},
    {'w', 166},
    {'a', 16},
    {'w', 258},
    {'walkDown', 1},
    {'w', 160},
    {'a', 24},
    {'w', 205},
    {'a', 19},
    {'w', 289},
    {'walkLeft', 1},
    {'w', 296},
    {'walkRight', 1},
    {'w', 119},
    {'walkDown', 1},
    {'w', 183},
    {'a', 19},
    {'w', 186},
    {'a', 25},
    {'w', 356},
    {'w', 378},
    {'b', 39},
    {'w', 115},
    {'b', 47},
    {'w', 177},
    {'b', 32},
    {'w', 108},
    {'b', 29},
    {'w', 278},
    {'walkLeft', 30}, -- go to department store
    {'w', 70},
    {'walkDown', 3},
    {'w', 25},
    {'walkLeft', 8},
    {'w', 41},
    {'walkUp', 1},
    {'w', 200},
    --mapChange
    {'walkUp', 9}, -- go into elevator
    {'walkLeft', 5},
    {'walkUp', 5},
    --mapChange
    {'w', 200},
    {'walkUp', 2}, -- go to buttons
    {'walkLeft', 3},
    {'walkUp', 1},
    {'a', 15}, -- select floor
    {'w', 247},
    {'walkDown', 3},
    {'w', 60},
    {'a', 18},
    {'w', 100},
    {'walkRight', 3},
    {'walkDown', 4}, -- get out of elevator
    {'w', 200},
    {'walkLeft', 4}, -- go to counter
    {'walkDown', 10},
    {'w', 201},
    {'a', 11}, -- buy thunderstone
    {'w', 185},
    {'a', 13},
    {'w', 277},
    {'walkDown', 1},
    {'walkDown', 1},
    {'walkDown', 1},
    {'w', 60},
    {'a', 17},
    {'w', 146},
    {'a', 15},
    {'w', 127},
    {'a', 13},
    {'w', 120},
    {'a', 13},
    {'w', 93},
    {'b', 14},
    {'w', 108},
    {'b', 14},
    {'w', 107},
    {'b', 13}, -- thunderstone purchased
    {'w', 60},
    {'walkUp', 9}, -- get back to elevator
    {'w', 183},
    {'walkRight', 4},
    {'w', 42},
    {'walkUp', 3},
    --mapChange
    {'w', 180},
    {'walkUp', 2}, -- go to panel
    {'walkLeft', 3},
    {'walkUp', 1},
    {'a', 15}, -- select 1F
    {'w', 60},
    {'walkDown', 3},
    {'a', 15},
    {'w', 180},
    {'walkRight', 3}, -- get out of elevator
    {'walkDown', 4},
    {'w', 180},
    {'walkDown', 5},
    {'walkRight', 5},
    {'walkDown', 10},
    --mapChange
    {'w', 180},
    {'w', 205},
    {'walkRight', 27},
    {'walkDown', 8},
    {'walkDown', 3},
    {'walkLeft', 11},
    {'walkDown', 6},
    {'walkRight', 11},
    {'walkLeft', 5},
    {'walkUp', 3},
    --mapChange
    {'w', 180}, -- go into resturant
    {'walkUp', 7},
    {'walkLeft', 5},
    {'a', 31}, -- get coin case
    {'w', 48},
    {'a', 31},
    {'w', 55},
    {'a', 39},
    {'w', 43},
    {'a', 37},
    {'w', 65},
    {'a', 33},
    {'w', 61},
    {'b', 43},
    {'w', 28},
    {'b', 28},
    {'b', 27},
    {'b', 20},
    {'b', 22}, -- coin case acquired
    {'w', 38},
    {'walkRight', 4}, -- leave resturant
    {'walkDown', 8},
    {'walkRight', 2},
    --mapChange
    {'walkDown', 2},
    {'w', 180}, -- go to casino
    {'walkLeft', 7},
    {'walkUp', 6},
    {'walkRight', 11},
    {'walkUp', 4},
    {'walkLeft', 8},
    {'walkUp', 2},
    --mapChange
    {'w', 180}, -- breakpoint - to rocket
    {'w', 251},
    {'s', 13}, -- move gyarados pulse and position
    {'w', 105},
    {'walkUp', 1},
    {'w', 175},
    {'a', 13},
    {'w', 193},
    {'walkRight', 1},
    {'w', 59},
    {'walkDown', 1},
    {'w', 60},
    {'a', 17},
    {'w', 63},
    {'a', 16},
    {'w', 246},
    {'walkRight', 1},
    {'w', 267},
    {'walkUp', 1},
    {'w', 153},
    {'walkDown', 1},
    {'w', 130},
    {'walkRight', 1},
    {'w', 256},
    {'a', 21},
    {'w', 265},
    {'walkDown', 1},
    {'w', 24},
    {'walkRight', 1},
    {'w', 64},
    {'walkDown', 1},
    {'w', 121},
    {'walkRight', 1},
    {'w', 65},
    {'walkDown', 1},
    {'w', 231},
    {'a', 20},
    {'w', 294},
    {'walkUp', 1},
    {'w', 34},
    {'walkRight', 1},
    {'w', 42},
    {'walkUp', 1},
    {'w', 27},
    {'walkRight', 1},
    {'w', 45},
    {'walkUp', 1},
    {'walkRight', 1},
    {'w', 93},
    {'a', 21},
    {'w', 558},
    {'b', 22},
    {'w', 166},
    {'b', 20},
    {'w', 344},
    {'walkDown', 1},
    {'w', 201},
    {'a', 14},
    {'w', 235},
    {'walkLeft', 1},
    {'w', 129},
    {'a', 13},
    {'w', 607},
    {'b', 19},
    {'w', 202},
    {'b', 17}, -- done with gyarados, menu on pokemon
    {'w', 60},
    {'w', 159},
    {'walkUp', 9},
    {'walkRight', 3},
    {'walkUp', 2}, -- go to rocket trainer
    {'w', 155}, -- start battle
    {'a', 12},
    {'w', 129},
    {'b', 17},
    {'w', 408},
    {'a', 16},
    {'w', 679}, -- wait for start w/ intimidate
    {'a', 16},
    {'use_move', 2}, -- use water pulse twice
    {'press_b', 7}, -- gyarados at 154/172 health due to quick attack
    {'walkUp', 2},
    {'a', 15},
    {'press_b', 4},
    {'walkRight', 6},
    {'w', 540}, -- enter rocket hideout
}
