sabrina = {
	{'w',30},
	{'w', 180},
    {'walkDown', 1},
    {'walkLeft', 18},
    {'walkDown', 8},
    {'walkRight', 9},
    {'walkUp', 2}, -- into pokecenter
    --mapChange
    -- silph-3
    {'w', 240},
    {'walkUp', 5},
    {'w', 30},
    {'pokecenter_heal', 1},
    {'w', 15},
    {'walkDown', 6},
    {'w', 210},
    {'walkLeft', 10}, -- go to saffron gym
    {'walkUp', 30},
    {'walkRight', 22},
    {'walkDown', 3},
    {'walkRight', 3},
    {'walkDown', 2},
    {'walkRight', 9},
    {'walkUp', 2}, -- enter gym
    --mapChange
    {'w', 180},
    {'walkRight', 5}, -- solve warp puzzle
    {'w', 33},
    {'walkUp', 4},
    {'w', 188},
    {'walkUp', 3},
    {'w', 151},
    {'walkDown', 4},
    {'w', 172},
    {'walkDown', 3},
    {'w', 196},
    {'walkUp', 4},
    {'w', 167},
    {'walkDown', 4},
    {'w', 164},
    {'walkUp', 4},
    {'w', 173},
    {'walkUp', 3},
    {'w', 143},
    {'walkDown', 4},
    {'w', 154},
    {'walkDown', 3},
    {'w', 156},
    {'walkUp', 4},
    {'w', 153},
    {'walkUp', 3},
    {'w', 160},
    {'walkUp', 3},
    {'w', 145},
    {'walkDown', 4},
    {'w', 165},
    {'walkDown', 3},
    {'w', 180},
    {'walkUp', 2}, -- exit into sabrina's room
    {'w', 60},
    {'walkLeft', 4},
    {'w', 44},
    {'walkUp', 2},
    {'w', 49},
    {'walkLeft', 2},
    {'w', 22},
    {'walkUp', 2},
    {'w', 34},
    {'a', 22},
    {'w', 125},
    {'b', 43},
    {'w', 35},
    {'b', 51},
    {'w', 52},
    {'b', 56},
    {'w', 46},
    {'b', 52},
    {'w', 443},
    {'b', 55},
    {'w', 440},
    {'b', 40},
    {'use_move', 4},
    {'press_b', 16},
    {'w', 213}, -- leave gym
    {'walkDown', 4},
    {'w', 22},
    {'walkRight', 5},
    {'w', 145},
    {'walkUp', 4},
    {'w', 138},
    {'walkDown', 1},
    {'w', 23},
    {'walkUp', 4},
    {'w', 146},
    {'walkDown', 4},
    {'w', 141},
    {'walkDown', 3},
    {'w', 145},
    {'walkDown', 3},
    {'w', 167},
    {'walkUp', 4},
    {'w', 152},
    {'walkUp', 3},
    {'w', 144},
    {'walkDown', 4},
    {'w', 156},
    {'walkDown', 3},
    {'w', 166},
    {'walkUp', 4},
    {'w', 151},
    {'walkDown', 4},
    {'w', 148},
    {'walkUp', 4},
    {'w', 185},
    {'walkUp', 3},
    {'w', 144},
    {'walkDown', 4},
    {'w', 180},
    {'walkDown', 4},
    {'walkLeft', 5},
    {'walkDown', 2},
    --mapChange
    {'w', 180},
    -- saffron-1


}
