kimono = {
	{'w',30},
	{'s',5}, -- switch to croconaw for kimono girls
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',120},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',180},
	{'mashB',5},
	{'walkDown',1},
	{'walkRight',12},
	{'walkUp',8},
	{'walkRight',7},
	{'walkUp',2},
	{'w',120}, -- in dance theater
	{'walkUp',6},
	{'walkLeft',5},
	{'walkUp',6},
	{'walkLeft',1},
	{'a',5},
	{'w',30},
	{'mashB',30}, -- Flareon
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'mashA',75},
	{'mashB',15}, -- evolves to feraligatr. now on to jolteon
	{'walkDown',2},
	{'walkRight',11},
	{'walkUp',1},
	{'s',5}, -- switch to kadabra and teach shadow ball
	{'w',120},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',60},
	{'walkDown',4},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'b',5},
	{'w',120},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'talk',5},
	{'walkUp',1},
	{'talk',7},
	{'walkDown',2},
	{'a',5},
	{'w',120},
	{'mashB',15},
	{'a',5}, -- jolteon
	{'w',30},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',30},
	{'walkLeft',3},
	{'walkUp',2},
	{'a',5}, -- vaporeon
	{'w',30},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',30},
	{'walkLeft',3},
	{'walkUp',2},
	{'walkLeft',5},
	{'a',5}, -- espeon. might not one-shot
	{'w',30},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'mashB',30}, 
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',30}, -- i guaranteed won
	{'walkDown',2},
	{'walkRight',3},

	{'a',5}, -- umbreon
	{'w',30},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'mashB',30}, -- used ice punch. may have beaten him and may not have. 
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',30}, -- i guaranteed won
	{'walkDown',3}, -- dont know where my character is so gonna go to bottom right
	{'w',180},
	{'walkRight',7},
	{'walkDown',9},  -- im at bottom right
	{'walkLeft',5},
	{'walkUp',3},
	{'a',5},
	{'w',30},
	{'mashB',40},
	{'walkLeft',2},
	{'walkDown',4},
	{'w',120},
	{'walkRight',4},
	{'walkDown',7},
	{'walkLeft',4},
	{'walkUp',2},
	{'w',120},
	{'pokemonCenter',1},
	{'w',120}, -- teach surf
	{'s',5},
	{'w',60},
	{'walkDown',2},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'walkDown',4},
	{'talk',5},
	{'walkDown',1},
	{'talk',8},
	{'mashB',20},
}
