firstBattles = 
{
	{"w",1},
	{"grassRight",5},
	{"grassUp",3},
	{"walkUp",6},
	{"walkLeft",8},
	{"walkUp",1},
	{"talk",3},
	{"w",480},
	{"talk",2},
	{"walkRight",8},
	{"walkUp",1},
	{"grassUp",6},
	{"walkUp",1},
	{"walkLeft",9},
	{"walkDown",1},
	{"resetMenu",1},
	{"s",5}, -- give berry for first fight
	{"w",60},
	{"walkDown",3},
	{"a",5},
	{"w",300}, -- on the item screen
	{"d",180}, -- hold down do make sure I'm on the bottom
	{"w",30},
	{"u",5},
	{"w",30},
	{"u",5},
	{"w",30},
	{"a",5},
	{"w",30},
	{"d",5},
	{"w",30},
	{"a",5},
	{"w",120},
	{"a",5},
	{"w",120},
	{"a",5},
	{"w",120},
	{"b",5},
	{"w",120},
	{"b",5},
	{"w",120},
	{"walkUp",6}, -- fight joey = spam scratch. guaranteed w and level 7
	{"talk",100},
	{"mashB",10},
	{"s",5},-- now delete his damn number
	{"w",60},
	{"d",5},
	{"w",30},
	{"d",5},
	{"w",30},
	{"d",5},
	{"w",30},
	{"a",5},
	{"w",120},
	{"deleteNumber",1},
	{"w",120},
	{"s",5}, -- add another berry
	{"w",60},
	{"u",5},
	{"w",30},
	{"a",5},
	{"w",180},
	{"d",180}, -- hold down do make sure I'm on the bottom
	{"w",30},
	{"u",5},
	{"w",30},
	{"u",5},
	{"w",30},
	{"a",5},
	{"w",60},
	{"d",5},
	{"w",30},
	{"a",5},
	{"w",180},
	{"talk",2},
	{"b",5},
	{"w",30},
	{"b",5},
	{"w",30},
	{"b",5},
	{"w",30},
	{"b",5},
	{"w",30},
	{"b",5},
	{"w",30},
	{"b",5},
	{"w",30}, -- berry added. time to go back to the pokemon center
	{"walkDown",6},
	{"walkLeft",2},
	{"walkDown",5},
	{"w",30},
	{"walkDown",3},
	{"walkRight",4},
	{"walkDown",7},
	{"w",30},
	{"walkDown",10},
	{"walkRight",14},
	{"walkUp",2}, -- in pokemon center
	{"w",300},
	{"walkUp",4},
	{"talk",6},
	{"w",720},
	{"talk",3},
	{"w",120},
	{"walkDown",6},
	{"w",480}, -- out of center
	{"walkLeft",13},
	{"walkUp",11},
	{"walkRight",1}, -- now back in the beginning of Rte 30
	{"grassRight",5},
	{"grassUp",3},
	{"walkUp",6},
	{"grassUp",6},
	{"walkUp",1},
	{"walkLeft",8},
	{"walkUp",10},
	{"talk",100}, -- fight mikey. because you beat rival, this is a guaranteed w
	{"b",5},
	{"w",120},
	{"b",5},
	{"w",120},
	{"b",5},
	{"w",120},
	{"b",5},
	{"w",120}, -- back to center
	{"walkDown",10},
	{"walkLeft",3},
	{"walkDown",5},
	{"w",30},
	{"walkDown",3},
	{"walkRight",4},
	{"walkDown",7},
	{"w",30},
	{"walkDown",10},
	{"walkRight",14},
	{"walkUp",2}, -- in pokemon center
	{"w",300},
	{"walkUp",4},
	{"talk",6},
	{"w",720},
	{"talk",3},
	{"w",120},
	{"walkDown",6},
	{"w",480}, -- out of center
	{"walkLeft",13},
	{"walkUp",11},
	{"walkRight",1}, -- now back in the beginning of Rte 30
	{"grassRight",5},
	{"grassUp",3},
	{"walkUp",6},
	{"grassUp",6},
	{"walkUp",1},
	{"walkLeft",8},
	{"walkUp",10}, -- in front of mikey
	{"walkLeft",4},
	{"walkUp",5},
	{"grassUp",5},
	{"grassLeft",1},
	{"walkLeft",1},
	{"walkUp",2},
	{"grassUp",4},
	{"w",600}, -- Don approaches
	{"talk",100}, -- scratch over and over once again optimal
	{"b",5},
	{"w",30},
	{"b",5},
	{"w",30},
	{"b",5},
	{"w",30},
	{"b",5},
	{"w",30},
	{"grassRight",1},
	{"walkRight",4},
	{"walkUp",7},
	{"walkRight",2},
	{"walkUp",6},
	{"w",600}, -- mom calls
	{"mashB",25},
	{"walkUp",3},
	{"walkRight",2},
	{"grassRight",5},
	{"grassUp",5},
	{"grassRight",2},
	{"walkRight",3},
	{"walkUp",5},
	{"walkLeft",8},
	{"walkUp",1},
	{"a",5},
	{"w",420},
	{"talk",2},
	{"w",30},
	{"walkDown",3},
	{"walkLeft",11},
	{"walkDown",5},
	{"walkLeft",2}, --Im gonna avoid this guy for now, he could be the next doug
	{"grassLeft",2},
	{"walkLeft",2},
	{"grassLeft",5},
	{"grassUp",3},
	{"walkUp",3},
	{"walkLeft",7},
	{"w",480},
	{"walkLeft",10}
}
