well = {
	{"w",300},
	{"walkLeft",7},
	{"walkUp",6},
	{"w",300},
	{"walkUp",4},
	{"talk",20},
	{"w",180},
	{"walkDown",5},
	{"w",300},
	{"walkDown",5},
	{"walkRight",200},
	{"walkUp", 6},
	{"walkLeft",3},
	{"walkUp",2},
	{"w",300}, -- time to buy an antidote
	{"walkUp",4},
	{"walkLeft",1},
	{"talk",2},
	{"w",240},
	{"walkDown",6},
	{"talk",1},
	{"walkUp",2},
	{"talk",2},
	{"mashB",10},
	{"walkDown",6},
	{"w",300},
	{"walkRight",3},
	{"walkDown",4},
	{"walkRight",9},
	{"walkUp",3},
	{"w",300}, -- well
	{"s",5},--use repel.
	{"w",120},
	{"walkUp",1}, -- start on pokegear
	{"a",5},
	{"w",300},
	{"walkDown",8},
	{"walkUp",5},
	{"talk",2},
	{"mashB",10},
	{"walkLeft",3},
	{"walkUp",6},
	{"w",480},
	{"talk",6},
	{"w",600},
	{"talk",1},
	{"w",240},
	{"talk",1},
	{"w",600},
	{"a",5},
	{"w",30}, -- now switch moves
	{"walkDown",1},
	{"se",5},
	{"w",60},
	{"se",5},
	{"w",60},
	{"talk",50},
	{"mashB",10},
	{"walkLeft",2},
	{"walkUp",7},
	{"talk",100},
	{"mashB",10},
	{"w",30}, -- time to apply the antidote... maybe!
	{"s",5},
	{"w",120},
	{"walkDown",2},
	{"w",480},
	{"walkDown",8},
	{"walkUp",1},
	{"w",30},
	{"talk",3},
	{"mashB",8},
	{"walkUp",2},
	{"walkLeft",4},
	{"talk",20},
	{"walkDown",4},
	{"walkLeft",5},
	{"talk",100},
	{"mashB",10},
	{"walkUp",2},
	{"walkLeft",3},
	{"walkUp",3},
	{"talk",150}, -- back at the dudes house with full health pkmn
	{"walkDown",5},
	{"w",300},
	{"walkDown",5},
	{"walkLeft",3},
	{"walkDown",6},
	{"walkRight",4},
	{"walkUp",2},
	{"w",300}, -- now in bugsy's gym
}
