finale = { 
	{'w',120}, -- finally, ready to go finght trainer red! need to do 3 things
	           -- talk to Oak to open up mt silver
			   -- grab a rare candy on way to mt silver and level Kad to 87
			   -- FIGHT RED!
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'talk',2},
	{'walkUp',1},
	{'a',5},
	{'w',420}, -- fly to pallet town to hit up oak
	{'walkRight',5},
	{'walkDown',7},
	{'walkRight',4},
	{'walkUp',2},
	{'w',120},
	{'walkUp',8},
	{'talk',27},
	{'w',300},
	{'mashB',10},
	{'walkDown',10},
	{'w',120},
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'talk',2},
	{'walkUp',2},
	{'a',5},
	{'w',420}, -- now walk from viridian to mt silver
	{'walkLeft',3},
	{'walkUp',11},
	{'walkLeft',6},
	{'walkDown',2},
	{'walkLeft',22},
	{'walkDown',4},
	{'walkLeft',5},
	{'walkUp',1}, -- now repel
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',8},
	{'talk',3},
	{'mashB',8},
	{'walkUp',7},
	{'walkLeft',14},
	{'walkDown',3},
	{'w',60},
	{'walkDown',4},
	{'walkLeft',5},
	{'walkUp',7},
	{'walkLeft',2},
	{'walkUp',2},
	{'w',120},
	{'walkUp',2},
	{'walkLeft',16},
	{'walkDown',4},
	{'w',120},
	{'walkLeft',6},
	{'walkDown',3},
	{'walkLeft',3},
	{'w',60},
	{'walkDown',3},
	{'walkLeft',8},
	{'walkUp',2},
	{'walkLeft',9},
	{'walkDown',3},
	{'w',60},
	{'walkLeft',15},
	{'walkDown',3},
	{'walkLeft',8},
	{'walkUp',5},
	{'walkLeft',5},
	{'walkUp',5},
	{'walkLeft',3},
	{'walkUp',6},
	{'w',120},
	{'pokemonCenter',1},
	{'w',120},
	{'walkDown',2}, -- get rare candy
	{'walkRight',9},
	{'walkDown',2},
	{'talk',4},
	{'w',240},
	{'walkDown',2},
	{'walkRight',4},
	{'walkUp',2},
	{'talk',4},
	{'w',240},
	{'walkUp',3},
	{'walkRight',12},
	{'walkDown',2},
	{'walkRight',17},
	{'walkUp',2},
	{'walkRight',5},
	{'walkUp',1},
	{'a',5},
	{'w',300},
	{'mashB',5}, 
	{'walkLeft',6},
	{'walkDown',2},
	{'walkLeft',6},
	{'mashB',3}, --repel wears off
	{'walkLeft',11},
	{'walkUp',2},
	{'walkLeft',11},
	{'walkDown',2},
	{'talk',4},
	{'w',240},
	{'walkDown',3},
	{'walkLeft',4},
	{'walkUp',1},
	{'talk',4},
	{'w',240},
	{'walkUp',3},
	{'walkLeft',11},
	{'s',5}, -- repel
	{'w',60},
	{'a',5},
	{'w',120},
	{'talk',3},
	{'walkUp',1}, -- rare candy time! get big, my kadabra!
	{'talk',2},
	{'walkUp',2},
	{'mashA',200},
	{'mashB',8},
	{'walkLeft',1},
	{'w',60},
	{'walkUp',11},
	{'walkLeft',2},
	{'walkUp',2}, -- in mt silver
	{'w',120},
	{'walkUp',7},
	{'walkRight',4},
	{'walkUp',5},
	{'walkLeft',9},
	{'walkUp',7},
	{'walkRight',5},
	{'walkDown',3},
	{'walkRight',8},
	{'walkUp',3},
	{'walkLeft',3},
	{'walkUp',12},
	{'walkLeft',6},
	{'walkUp',5},
	{'walkRight',5},
	{'walkDown',3},
	{'walkRight',4},
	{'walkUp',6},
	{'w',120}, -- second room
	{'walkRight',3},
	{'walkUp',16},
	{'walkLeft',14},
	{'walkUp',9},
	{'walkRight',6},
	{'walkUp',4},
	{'w',120},
	{'walkRight',2},
	{'walkUp',20},
	{'walkLeft',2},
	{'walkUp',4},
	{'a',5},
	{'w',30},
	{'mashB',30}, -- RED! Pikachu is one-shot by psychic
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',40}, -- Espeon out. first, guard spec
	{'walkDown',1},
	{'a',5},
	{'w',60},
	{'walkDown',14},
	{'talk',4},
	{'mashB',35}, -- now heal (or not!)
	{'a',5},
	{'w',60},
	{'walkUp',10},
	{'talk',4},
	{'mashB',45}, -- either nothing happened or i healed
	{'a',5}, -- X Spec 1
	{'w',60},
	{'walkDown',5},
	{'talk',4},
	{'mashB',35},
	{'a',5},
	{'w',60}, -- heal again
	{'walkUp',5},
	{'talk',4},
	{'mashB',45},
	{'a',5},
	{'w',60}, -- X SPEC 2
	{'walkDown',5},
	{'talk',4},
	{'mashB',35},
	{'a',5},
	{'w',60}, -- heal again
	{'walkUp',5},
	{'talk',4},
	{'mashB',45},
	{'a',5},
	{'w',60}, -- X SPEC 3
	{'walkDown',5},
	{'talk',4},
	{'mashB',35},
	{'walkUp',1}, -- ok, now the BIG SWEEP
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'mashB',45}, -- fire punch kill. snorlax out. falls to psychic
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',55}, -- charizard easy 1-shot
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',45}, -- blastoise easy 1-shot
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',45}, -- venusaur easy one-shot
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',45},
	{'w',30}, -- GG!
}
