viridian = {
	{'w',30}, -- outside Sabrina's gym. time to get a few EXP before fighting blue (need 4854)
	          -- bike road has Weezing guy -- 1260 EXP
			  -- glenn 684 + 1072 + 1185
			  -- last guy 732 + 912 + 1111
	{'s',5}, -- fly to celadon
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'talk',2},
	{'walkDown',4},
	{'a',5},
	{'w',420}, 
	{'walkLeft',28},
	{'walkDown',16},
	{'walkLeft',10},
	{'w',120},
	{'walkLeft',10},
	{'w',120}, -- on cycle road
	{'walkLeft',4},
	{'walkDown',12},
	{'w',300}, -- WHEEE
	{'l',60},
	{'a',5}, -- first trainer of 3
	{'w',30},
	{'mashB',30},
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'r',600},
	{'w',300},
	{'l',300},
	{'a',30},
	{'w',30},
	{'mashB',30}, -- second guy
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',45},
	{'w',300}, -- im zoomin
	 -- in case im stuck at the last guy, go back to celadon to reset trainer position
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'talk',2},
	{'walkDown',4},
	{'a',5},
	{'w',420},
	{'walkLeft',28},
	{'walkDown',16},
	{'walkLeft',10},
	{'w',120},
	{'walkLeft',10},
	{'w',120},
	{'d',1800};
	{'w',120},
	{'l',420},
	{'w',30},
	{'r',30},
	{'w',120},
	{'r',30},
	{'w',120},
	{'r',30},
	{'w',120},
	{'a',5},
	{'w',30},
	{'mashB',30}, -- last guy
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'talk',2},
	{'walkUp',2},
	{'a',5},
	{'w',420}, -- in viridian. head to mart for Hyper pots after pokecentering
	{'walkUp',2},
	{'w',120},
	{'pokemonCenter',1},
	{'w',120},
	{'walkRight',7},
	{'walkUp',8},
	{'w',120},
	{'walkUp',4},
	{'walkLeft',1},
	{'talk',2},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',60},
	{'walkUp',5},
	{'talk',3},
	{'mashB',10},
	{'walkDown',6},
	{'w',120},
	--because of a wanderer i need to come up with some way to get here with high propability
	{'walkLeft',9},
	{'walkUp',5},
	{'walkLeft',3},
	{'u',1200},
	{'w',30}, -- should be up against the sign. 
	{'walkDown',5},
	{'walkRight',50}, -- either I am stuck on old man or between gym and sign.
		-- if I am not correctly near gym, I need to repeat down one step -> walk right 
		-- eventually this will work. I'll do it 20 times
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50},
	{'walkDown',2}, 
	{'walkRight',50}, -- now im at the sign
	{'walkUp',4},
	{'walkRight',8},
	{'walkDown',6},
	{'walkLeft',3},
	{'walkUp',2},
	{'w',120},
	{'walkUp',14},
	{'walkRight',1}, -- im in front of blue!
	{'a',5},
	{'w',30},
	{'mashB',45}, -- ok, here's Pidgeot. might QA. just knock out with ice punch
				  -- QA does max 82, so I have at least 91 HP
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'mashB',50}, -- alakazam is out. I can either 2shot with X-SPEC or one-shot
				  -- he has disable, psychic, reflect, recover
				  -- disable will disable ice punch here if used. that's nbd, i just wont use it
				  -- least variability then is X-SPEC + fire punch or thunder punch
				  -- Reflect? useless bc I only use special moves. recover useless if i one-shot
				  -- if it uses psychic, only does at most 49. so this is safe
	{'walkDown',1}, -- X-Spec
	{'a',5},
	{'w',120},
	{'walkDown',14},
	{'talk',4},
	{'mashB',20},
	{'walkUp',1}, -- use fire punch
	{'a',5},
	{'w',30},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'mashB',50}, -- Rhydon. One-shot with Psychic
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',50}, -- Gyarados. EASY thunderpunch
	{'a',5},
	{'w',30},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'mashB',50}, -- Egg. Fire punch
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30}, -- now arcanine. extremespeed easily KOs me, so I do need to switch here
	{'mashA',40}, -- send in kenya so I can hyper pot brian if needed
	{'w',60},
	{'walkDown',2},
	{'a',5},
	{'w',60},
	{'walkDown',2},
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',30},
	{'mashB',20}, -- kenya out
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkUp',5},
	{'talk',2}, -- if it didn't work, need to go back and try to use peck
	{'walkUp',2},
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'b',5},
	{'w',120},
	{'walkUp',1},
	{'a',4},
	{'w',30},
	{'a',5},
	{'w',30},
	{'w',30},
	{'mashB',30},
	{'w',60},
	{'a',5},
	{'w',30},
	{'mashB',20}, -- brian out. use psychic for the kill
	{'a',5},
	{'w',30},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'mashB',80},
	{'w',30},
	{'walkDown',16},
	{'w',120}, -- I got all the badges!! only RED remains. WOOO! but also, AHHH!
}
