gym8 = {
	{'w',5},
	{'w',120},
	{'walkUp', 7},
	{'walkLeft', 4},
	{'walkUp', 3},
	{'walkLeft', 2},
	{'walkUp', 4},
	{'walkRight', 3},
	{'walkUp', 4}, -- fight first trainer
	{'w', 247},
	{'b', 20},
	{'w', 437},
	{'b', 21},
	{'w', 438},
	{'a', 18},
	{'use_move', 5}, -- defeat them w/ ice beam 5/10
	{'press_b', 6},
	{'s', 10}, -- switch charizard to front
	{'w', 60},
	{'a', 26},
	{'w', 80},
	{'a', 15},
	{'w', 15},
	{'walkDown', 1},
	{'a', 15},
	{'walkRight', 1},
	{'a', 15},
	{'w', 50},
	{'press_b', 6}, -- done switching
	{'w', 60},
	{'walkUp', 1},
	{'walkLeft', 4},
	{'walkDown', 2},
	{'walkLeft', 3},
	{'walkUp', 3}, -- fight karate king
	{'w', 188},
	{'b', 19},
	{'w', 425},
	{'b', 23},
	{'w', 391},
	{'a', 15},
	{'walkRight', 1},
	{'use_move', 3},
	{'w', 90},
	{'walkDown', 3},
	{'walkRight', 4},
	{'walkUp', 2},
	{'walkRight', 4},
	{'walkDown', 5},
	{'walkLeft', 4},
	{'walkDown', 4},
	{'walkRight', 2},
	{'walkDown', 4},
	{'walkRight', 6},
	{'walkUp', 3},
	{'w', 180},
	{'walkUp', 1},
	{'w', 90},
	{'walkLeft', 4},
	{'walkDown', 5},
	{'walkLeft', 6},
	{'walkUp', 4}, -- approach giovanni
	{'w', 30},
	{'s', 10}, -- switch articuno to front
	{'w', 60},
	{'a', 26},
	{'w', 80},
	{'a', 15},
	{'w', 15},
	{'walkDown', 2},
	{'a', 15},
	{'walkRight', 1},
	{'a', 15},
	{'w', 50},
	{'press_b', 6}, -- done switching
	{'w', 30},
	{'a', 17}, -- talk to giovanni
	{'w', 71},
	{'b', 29},
	{'w', 79},
	{'b', 24},
	{'w', 82},
	{'b', 23},
	{'w', 67},
	{'b', 25},
	{'w', 68},
	{'b', 26},
	{'w', 411}, -- battle starts
	{'b', 20},
	{'w', 452},
	{'use_move', 5}, -- 5 ice beams take care of it
	{'press_b', 23}, -- get badge
	{'walkDown', 4},
	{'walkRight', 6},
	{'walkUp', 4},
	{'walkRight', 7},
	{'w', 90},
	{'walkRight', 1},
	{'w', 150},
	{'walkDown', 4},
	{'walkLeft', 2}, 
	{'walkDown', 6}, -- leave gym
	--mapChange
	{'w', 180},
	{'walkDown', 1},
	{'w', 90},
	{'walkLeft', 15},
	{'walkDown', 15},
	{'walkRight', 5},
	{'walkUp', 2},
	--mapChange
	{'w', 180},
	{'walkUp', 6},
	{'w', 30},
	{'pokecenter_heal',1},
	{'w', 30},
	{'walkDown', 6},
	{'w', 180},
	-- viridian-2

}
