paras = {
	{'w',5}, 
	-- order of events
	-- fly to mt moon
	-- teach jolteon toxic
	-- give jolteon cheri beri
	-- grab thief
	-- head to b1f
	-- paras!
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyLeft',3},
	{'flyUp',3},
	{'a',5},
	{'w',480},
	{'walkRight',8},
	{'walkUp',2},
	{'w',300}, -- in mt moon
	{'s',5}, -- repel
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkUp',8},
	{'talk',3}, -- used repel. while were here, teach jolteon toxic
	{'walkRight',1},
	{'talk',2},
	{'w',30},
	{'walkDown',4},
	{'talk',2},
	{'w',30},
	{'walkDown',2},
	{'talk',5},
	{'w',60},
	{'walkUp',2},
	{'a',5},
	{'w',240},
	{'mashB',20},
	{'s',5}, -- give our friend the cheri berry
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkDown',10},
	{'talk',3},
	{'walkDown',1},
	{'talk',4},
	{'mashB',10},
	{'walkUp',12},
	{'walkRight',6},
	{'walkUp',10},
	{'walkRight',8},
	{'walkUp',2},
	{'walkRight',7},
	{'walkUp',7},
	{'walkLeft',18},
	{'walkDown',6},
	{'w',180},
	{'walkLeft',9},
	{'walkDown',2},
	{'w',180},
	{'walkRight',5},
	{'walkUp',6},
	{'a',5}, -- thief
	{'w',30},
	{'mashB',6},
	{'walkDown',6},
	{'walkLeft',5},
	{'w',180}, -- up to B1F!
	{'walkRight',9},
	{'mashB',3}, -- repel off. now flounder around for paras
	{'flounder',100},
	{'a',5},
	{'w',180}, -- jolteon out against paras
	{'walkRight',1}, 
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'walkDown',9},
	{'talk',3},
	{'mashB',30},
	{'walkLeft',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'mashB',30}, -- toxiced. now pokeflute stall
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'walkUp',3},
	{'talk',2},
	{'mashB',30}, -- second turn of paras pain. flute one more time
	{'a',5},
	{'w',120},
	{'talk',2},
	{'mashB',30}, -- now we can catch with UB
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'walkDown',1},
	{'talk',2},
	{'w',480},
	{'mashB',60}, -- PARAS!
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkLeft',2},
	{'walkUp',1},
	{'talk',3},
	{'w',480}, -- out of mt moon
}
