pidgey = {
	{'w',5},
	-- start in front of mt moon. order of events
	-- fly to Viridian
	-- heal in case Jolteon was paralyzed by paras
	-- take out aerodactyl
	-- go to rte 1
	-- get pidgey with toxic strats. pretty simple
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyLeft',5},
	{'flyDown',5},
	{'a',5},
	{'w',480},
	{'walkUp',1},
	{'w',180}, -- in viridian Pokemon Center
	{'walkUp',4},
	{'talk',3},
	{'w',360},
	{'mashB',8},
	{'walkRight',5},
	{'walkUp',3},
	{'talk',5},
	{'walkDown',2},
	{'a',5},
	{'w',120}, -- in box
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',60},
	{'walkUp',2},
	{'a',5},
	{'w',60},
	{'walkUp',3},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',60},
	{'b',5},
	{'w',60},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',60},
	{'mashB',12}, -- done with box shenanegans
	{'walkDown',4},
	{'walkLeft',5},
	{'walkDown',5},
	{'w',180},
	{'walkDown',3},
	{'w',60},
	{'walkDown',4},
	{'walkLeft',2},
	{'walkDown',10}, -- now repel
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkUp',8},
	{'talk',3},
	{'mashB',8},
	{'walkDown',1},
	{'w',60},
	{'s',5}, -- in grass. now switch to aerodactyl
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',60},
	{'mashB',6},
	{'flounder',400}, -- find that pidgey!
	{'a',5},
	{'w',360},
	{'walkRight',1}, -- use guard spec
	{'a',5},
	{'w',120},
	{'walkDown',10},
	{'talk',3},
	{'mashB',25},
	{'walkDown',1},
	{'walkLeft',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'talk',2},
	{'mashB',25}, -- jolteon out
	{'walkRight',1},
	{'a',5},
	{'w',120}, -- now XAcc
	{'talk',3},
	{'mashB',25},
	{'walkLeft',1}, -- toxic
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'mashB',25}, -- now ultra ball
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkRight',2},
	{'talk',2},
	{'mashB',70},
	{'w',30},
}
