raticate = {
	{'w',5},
	-- fly to daycare
	-- raise aerodactyl to 25
	-- teach aerodactyl thief
	-- encounter raticate
	-- Thief -> switch to Jolt -> XAcc -> Toxic -> Stall -> Ultra Ball
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkDown',3},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120}, -- fly to cerulean
	{'flyRight',5},
	{'a',5},
	{'w',480},
	{'walkDown',4},
	{'walkLeft',4},
	{'walkDown',7},
	{'walkRight',8},
	{'walkDown',2},
	{'talk',4}, -- cut tree
	{'w',300},
	{'walkDown',5},
	{'w',60},
	{'walkDown',7},
	{'w',60}, -- repel is still active
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',4},
	{'walkUp',1},
	{'w',180}, -- in daycare
	{'walkUp',2},
	{'talk',4},
	{'w',60},
	{'talk',2}, -- aero has 1536 EXP. needs 19531 total
	{'w',60},
	{'talk',2},
	{'w',60},
	{'walkDown',4}, 
	{'w',180},
	{'walkDown',1},
	{'w',60}, 
	{'walkDown',1},
	{'walkRight',5}, 
	{'mashB',3}, -- repel
	{'walkRight',5},
	{'walkDown',4},  
	{'walkRight',3}, 
	{'walkUp',1}, 
	{'w',180},
	{'walkRight',2}, 
	{'walkUp',5},    
	{'walkLeft',1},
	{'w',180}, -- the hallway is 59 steps long. we get 57 on the first round and 59 for each round after
	{'s',5}, -- bike time
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'talk',2},
	{'w',180},
	{'bike_daycare',152},
	{'walkDown',1},
	{'walkRight',1},
	{'w',180},
	{'walkDown',5},
	{'walkLeft',2},
	{'walkDown',2},
	{'w',180},
	{'walkLeft',3},
	{'walkUp',39},
	{'walkLeft',3},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6},
	{'s',5}, -- repel
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'talk',3},
	{'mashB',10},
	{'walkDown',1},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',5},
	{'walkUp',1},
	{'w',180},
	{'walkUp',2},
	{'talk',7}, -- aerodactyl is home :) 
	{'w',30},
	{'walkDown',4},
	{'w',180}, -- now fly to rat world
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120}, -- to rte 16
	{'flyDown',1},
	{'flyLeft',3},
	{'a',5},
	{'w',480},
	{'walkLeft',30},
	{'walkDown',4},
	{'walkLeft',15},
	{'walkDown',8},
	{'walkLeft',13},
	{'walkUp',1},
	{'talk',4},
	{'w',300},
	{'walkUp',5},
	{'walkLeft',1}, -- in position. repel still on!
	{'s',5}, -- teach thief
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'walkUp',3},
	{'talk',2},
	{'w',30},
	{'walkDown',8},
	{'talk',2},
	{'w',30},
	{'walkDown',3},
	{'talk',5},
	{'w',60},
	{'a',5},
	{'w',30},
	{'mashB',40},
	{'s',5}, -- switch aero to front
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'mashB',10},
	{'flounder',400}, -- get that rat
	{'w',30},
	{'a',5},
	{'w',300},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30}, -- thief. does some damage.
	{'mashB',30},
	{'walkDown',1}, -- Pokemon
	{'a',5},
	{'w',120},
	{'walkDown',3},
	{'talk',2},
	{'mashB',30}, -- now XAcc
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'walkDown',9},
	{'talk',3},
	{'mashB',20}, -- now toxic
	{'walkLeft',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'mashB',20}, -- one turn passed. pokeflute thrice
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'walkDown',7},
	{'talk',2},
	{'mashB',30}, -- second turn of toxic
	{'a',5},
	{'w',120},
	{'talk',2},
	{'mashB',30}, -- third turn of toxic
	{'a',5},
	{'w',120},
	{'talk',2},
	{'mashB',30}, -- now ultra ball
	{'a',5},
	{'w',120},
	{'walkRight',1},
	{'walkUp',2},
	{'talk',2},
	{'mashB',60},
}
