spearow = {
	{'w',1},
	-- need lvl 8 aerodactyl
	-- go to day care
	-- run to level 8
	-- take out aero
	-- fly to rte 3
	-- catch spearow with toxic
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'a',5}, -- switch aero with jolteon for repel to work by daycare
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',120},
	{'walkDown',3},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120}, -- fly to cerulean
	{'flyRight',10},
	{'flyUp',6},
	{'a',5},
	{'w',480},
	{'walkDown',4},
	{'walkLeft',4},
	{'walkDown',7},
	{'walkRight',8},
	{'walkDown',2},
	{'talk',4}, -- cut tree
	{'w',300},
	{'walkDown',5},
	{'w',60},
	{'walkDown',7},
	{'w',60}, -- repel is still active
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',4},
	{'walkUp',1},
	{'w',180}, -- in daycare
	{'walkUp',2},
	{'talk',4},
	{'w',60},
	{'walkDown',2},
	{'talk',2},
	{'w',60},
	{'talk',2},
	{'w',60}, 
	{'walkDown',4}, 
	{'w',180},
	{'walkDown',1},
	{'w',60}, 
	{'walkRight',7}, 
	{'walkDown',5},  
	{'walkRight',3}, 
	{'walkUp',1}, 
	{'w',180},
	{'walkRight',2}, 
	{'walkUp',5},    
	{'walkLeft',1},
	{'w',180}, -- the hallway is 59 steps long. we get 57 on the first round and 59 for each round after
	{'s',5}, -- bike time
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'walkUp',4},
	{'talk',2},
	{'mashB',5},
	{'d',180}, -- repel
	{'w',5},
	{'b',5},
	{'w',5},
	{'d',360}, -- 75 steps
	{'w',5},
	{'u',360}, -- 134 steps
	{'w',5},
	{'bike_daycare',3}, -- 488 steps. now leave
	{'walkDown',1},
	{'walkRight',1},
	{'w',180},
	{'walkDown',5},
	{'walkLeft',2},
	{'walkDown',2},
	{'w',180},
	{'walkLeft',3},
	{'walkUp',39},
	{'walkLeft',3},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6},
	{'s',5}, -- repel
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'walkUp',9},
	{'talk',3},
	{'mashB',10},
	{'walkDown',1},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',5},
	{'walkUp',1},
	{'w',180},
	{'walkUp',2},
	{'talk',7}, -- aerodactyl is home :) has total 728 EXP
	{'w',30},
	{'walkDown',4},
	{'w',180},
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkUp',3},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyLeft',6},
	{'flyUp',2},
	{'a',5},
	{'w',480},
	{'walkDown',24},
	{'mashB',3},
	{'walkRight',2}, -- in grass on route 3. spearow time. switch to aero
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkUp',2},
	{'a',5},
	{'w',60},
	{'mashB',10},
	{'flounder',200},
	{'a',5}, -- spearow
	{'w',240},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'talk',2}, -- switch to jolteon
	{'mashB',20},
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkDown',9}, -- x acc
	{'talk',2},
	{'mashB',20},
	{'walkLeft',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'mashB',20}, -- toxic. now ball
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkRight',2},
	{'talk',2},
	{'mashB',70}, -- now we do it again. we need two spearow. one to trade for farfetchd
	{'w',30},
	{'walkUp',1},
	{'w',60}, -- need to do this to maintain number of steps depending on which dir we were facing
	{'walkLeft',1},
	{'flounder',200},
	{'a',5}, -- spearow
	{'w',240},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkUp',2},
	{'talk',2}, -- switch to jolteon
	{'mashB',20},
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkLeft',2}, -- x acc
	{'talk',2},
	{'mashB',20},
	{'walkLeft',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'mashB',20}, -- toxic. now ball
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkRight',2},
	{'talk',2},
	{'mashB',70},
	{'w',30},
}
