zubat = {
	{'w',1},
	-- change charizard to front so that repel works
	-- go to daycare
	-- train Aerodactyl to LVL 10
	-- go to mt moon
	-- catch zubat using repel trick and nest ball
	{'s',5},
	{'w',60},
	{'a',5}, -- change charizard
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',3},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyRight',6},
	{'flyUp',1}, -- in cerulean
	{'a',5},
	{'w',480},
	{'walkDown',4},
	{'walkLeft',4},
	{'walkDown',7},
	{'walkRight',8},
	{'walkDown',2},
	{'talk',4}, -- cut tree
	{'w',300},
	{'walkDown',5},
	{'w',60},
	{'walkDown',7},
	{'w',60}, -- repel is still active
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',3}, -- repel off
	{'mashB',3},
	{'w',30},
	{'walkDown',3},
	{'walkLeft',4},
	{'walkUp',1},
	{'w',180}, -- in daycare
	{'walkUp',2},
	{'talk',4},
	{'w',60},
	{'walkDown',1},
	{'talk',2},
	{'w',60},
	{'talk',2},
	{'w',60}, 
	{'walkDown',4}, 
	{'w',180},
	{'walkDown',1},
	{'w',60}, 
	{'walkRight',7}, 
	{'walkDown',5},  
	{'walkRight',3}, 
	{'walkUp',1}, 
	{'w',180},
	{'walkRight',2}, 
	{'walkUp',5},    
	{'walkLeft',1},
	{'w',180}, 
	{'s',5}, -- bike time
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'talk',2},
	{'mashB',5},
	{'bike_daycare',6}, 
	{'walkDown',1},
	{'walkRight',1},
	{'w',180},
	{'walkDown',5},
	{'walkLeft',2},
	{'walkDown',2},
	{'w',180},
	{'walkLeft',3},
	{'walkUp',39},
	{'walkLeft',3},
	{'walkDown',3},
	{'w',60},
	{'walkDown',6},
	{'s',5}, -- repel
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkLeft',1},
	{'walkUp',9},
	{'talk',3},
	{'mashB',10},
	{'walkDown',1},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',4},
	{'w',60},
	{'walkDown',6},
	{'walkLeft',5},
	{'walkUp',1},
	{'w',180},
	{'walkUp',2},
	{'talk',7}, -- aerodactyl is home :) has total 728 EXP
	{'w',30},
	{'walkDown',4},
	{'w',180},
	{'s',5},
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkUp',4},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'flyLeft',6},
	{'flyUp',2},
	{'a',5},
	{'w',480},
	{'walkRight',8},
	{'walkUp',2},
	{'w',300},
	{'walkUp',1},
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'walkUp',2},
	{'a',5},
	{'w',120},
	{'mashB',8},
	{'flounder',300}, -- get to zubat
	{'a',5},
	{'w',300},
	{'walkRight',1},
	{'a',5},
	{'w',120},
	{'walkRight',2},
	{'walkDown',2},
	{'talk',2},
	{'mashB',60},
	{'walkDown',4},
	{'w',180},
}
