den = {
	{'w',30}, -- outside the gym. now use repel and teach whirlpool
	{'s',5},
	{'w',60},
	{'walkDown',2},
	{'a',5},
	{'w',120},
	{'walkDown',7},
	{'talk',3},
	{'walkLeft',1},
	{'walkDown',9},
	{'a',5},
	{'talk',5},
	{'w',120},
	{'walkDown',1},
	{'talk',7},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'mashB',15},
	{'walkLeft',3},
	{'talk',3},
	{'w',120},
	{'walkUp',7},
	{'walkRight',6},
	{'walkUp',4},
	{'w',120},
	{'walkUp',2},
	{'w',120},
	{'walkUp',2},
	{'w',120},
	{'walkDown',4},
	{'w',420},--trainer in den
	{'mashB',30}, 
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'walkLeft',9},
	{'walkDown',4},
	{'walkLeft',3},
	{'walkDown',1},
	{'talk',3},
	{'w',120},
	{'walkDown',11},
	{'talk',4},
	{'w',420},
	{'walkDown',10},
	{'walkRight',4},
	{'walkDown',2},
	{'walkRight',2},
	{'w',120},
	{'walkRight',5},
	{'walkUp',2},
	{'w',480}, -- quiz time
	{'talk',9},
	{'walkDown',2},
	{'talk',3},
	{'walkDown',1},
	{'talk',4},
	{'walkDown',2},
	{'talk',8},
	{'walkDown',1},
	{'talk',8},
	{'w',480}, -- clair shows up
	{'mashB',100},
	{'walkDown',8},
	{'w',480}, -- clair again...
	{'mashB',50}, -- now grab dratini
	{'walkUp',2},
	{'w',120},
	{'walkUp',8},
	{'walkRight',1},
	{'talk',6},
	{'w',360},
	{'talk',2},
	{'walkLeft',4},
	{'a',5},
	{'w',30}, -- F
	{'walkDown',2},
	{'walkLeft',3},
	{'a',5},
	{'w',30}, -- U
	{'walkUp',2},
	{'walkLeft',1},
	{'a',5},
	{'w',30}, -- B
	{'walkLeft',2},
	{'a',5},
	{'w',30}, -- I
	{'walkDown',1},
	{'walkLeft',4},
	{'a',5},
	{'w',30}, -- N
	{'walkRight',4},
	{'walkUp',1},
	{'a',5},
	{'w',30},
	{'s',5},
	{'a',5},
	{'w',60},
	{'mashB',15},
	{'walkDown',10},
	{'w',120},
	{'walkLeft',6},
	{'talk',3},
	{'w',120},
	{'walkUp',3},
	{'walkLeft',4},
	{'walkUp',4}, -- repel wears off
	{'mashB',3},
	{'s',5},
	{'w',60},
	{'walkDown',2},
	{'a',5},
	{'w',120},
	{'walkDown',7},
	{'talk',2},
	{'mashB',8},
	{'walkUp',4},
	{'talk',4},
	{'w',420},
	{'walkUp',14},
	{'w',60},
	{'walkRight',4},
	{'walkUp',4},
	{'walkRight',8},
	{'walkUp',2},
	{'w',120},
	{'walkUp',2},
	{'w',120},
	{'walkDown',4},
	{'w',600}, -- out of den, Elm calls
	{'mashB',35},
	{'s',5}, -- fly to littleroot
	{'w',60},
	{'walkUp',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'talk',3},
	{'w',600}, -- in littleroot 
	{'walkLeft',8},
	{'walkUp',4},
	{'w',120}, -- in the lab. getting master ball!
	{'walkUp',9},
	{'walkRight',1},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'walkDown',11},
	{'w',120},
}
