suicune = {
	{'w',30}, -- in front of lab. time to fly off to Cianwood and battle Eusine.
	{'s',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'a',5},
	{'w',60},
	{'a',5},
	{'w',120},
	{'walkDown',4},
	{'a',5},
	{'w',480},
	{'walkRight',4},
	{'walkUp',7},
	{'walkLeft',2},
	{'walkUp',5},
	{'walkLeft',3},
	{'walkUp',3},
	{'walkLeft',10},
	{'walkUp',5},
	{'walkLeft',8},
	{'mashB',3}, -- repel from earlier wears off
	{'walkUp',11},
	{'walkRight',5},
	{'walkUp',3},
	{'w',480}, -- Eusine!
	{'mashB',55},
	{'a',5},
	{'w',30},
	{'walkDown',2}, -- shadow ball on drowzee
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkUp',2}, -- psybeam
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30},
	{'mashB',50}, -- bye Eusine! time to go to Ecruteak
	{'s',5},
	{'w',60},
	{'walkDown',1},
	{'a',5},
	{'w',120},
	{'walkDown',2},
	{'talk',2},
	{'walkUp',5},
	{'a',5},
	{'w',480},
	{'walkRight',4},
	{'walkUp',13},
	{'walkLeft',6},
	{'walkUp',5},
	{'walkLeft',4},
	{'walkUp',2},
	{'w',120},
	{'walkUp',10}, -- in the pre-tower building
	{'a',5},
	{'w',30},
	{'mashB',30},
	{'walkRight',2},
	{'walkUp',5},
	{'w',120},
	{'walkUp',12},
	{'w',120},
	{'walkRight',4},
	{'w',120}, -- trio time
	{'mashB',50},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'mashB',70}, -- next guy
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'mashB',95}, -- next guy
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'mashB',70}, -- I'm done!
	{'walkRight',4},
	{'w',120},
	{'walkRight',9},
	{'walkDown',4},
	{'walkRight',5},
	{'walkDown',3},
	{'walkRight',3},
	{'walkDown',3},
	{'walkRight',3},
	{'walkUp',3}, -- in tower. long cutscene. about 15 seconds
	{'w',900},
	{'mashB',30}, -- now use master ball, young one
	{'walkDown',1},
	{'a',5},
	{'w',60},
	{'walkRight',1},
	{'walkDown',2},
	{'talk',2},
	{'w',900}, -- very long cutscene for the catch
	{'talk',6}, -- now name suicune MOLTISANTI
	{'walkDown',1},
	{'walkRight',3},
	{'a',5},
	{'w',30},
	{'walkRight',2},
	{'a',5},
	{'w',30},
	{'walkLeft',3},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'walkLeft',1},
	{'a',5},
	{'w',30},
	{'walkLeft',2},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkRight',1},
	{'walkDown',2},
	{'a',5},
	{'w',30},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'walkDown',1},
	{'walkRight',4},
	{'a',5},
	{'w',30},
	{'walkLeft',3},
	{'walkDown',1},
	{'a',5},
	{'w',30},
	{'walkLeft',2},
	{'walkUp',2},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',600},
	{'mashB',45}, -- goodbye, Eusine
	{'w',120},
}
