victoryroad = {
	{'w',30}, -- start by repelling and teaching fire punch
	{'s',5},
	{'w',60},
	{'walkDown',2},
	{'a',5},
	{'w',120},
	{'walkDown',8},
	{'talk',3}, -- use repel
	{'walkLeft',1},
	{'walkUp',8},
	{'talk',13},
	{'mashB',12},
	{'walkLeft',3},
	{'walkUp',8},
	{'walkRight',5},
	{'walkUp',7},
	{'walkLeft',5},
	{'walkDown',3},
	{'walkLeft',6},
	{'walkUp',8},
	{'walkLeft',2},
	{'w',120},
	{'walkDown',4},
	{'walkRight',5},
	{'walkUp',3},
	{'walkRight',5},
	{'walkDown',5},
	{'walkRight',5},
	{'walkDown',3},
	{'walkLeft',7},
	{'walkUp',4},
	{'a',5},
	{'w',180},
	{'mashB',5}, -- HP UP
	{'walkDown',4},
	{'walkRight',12},
	{'walkUp',7},
	{'walkLeft',6},
	{'walkUp',6},
	{'w',120},
	{'walkUp',1},
	{'walkRight',6},
	{'walkUp',7},
	{'walkLeft',6},
	{'walkUp',3},
	{'w',300}, -- KEVIN!
	{'mashB',70},
	{'a',5},
	{'w',30},
	{'a',5},
	{'w',30}, -- sneasel dies to firepunch
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkUp',1}, -- psychic for golbat
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkDown',1}, -- firepunch magneton
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkUp',1}, -- psychic for haunter
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkUp',1}, -- shadow ball for kad
	{'a',5},
	{'w',30},
	{'mashB',35},
	{'a',5},
	{'w',30},
	{'walkUp',2}, -- fire punch for meganium
	{'a',5},
	{'w',30},
	{'mashB',75},
	{'walkUp',4},
	{'w',120},
	{'walkUp',8},
	{'w',120}, -- at the e4!
	{'walkUp',4},
	{'walkLeft',3},
	{'walkUp',1},
	{'talk',7},
	{'w',300},
	{'mashB',12},
	{'w',30},
}
