seafoam = {
	{'w',5},
	{'w', 230}, 
    {'walkLeft', 4}, -- go to water route
    {'walkDown', 3},
    {'walkLeft', 2},
    {'walkDown', 4},
    {'walkRight', 8},
    --mapChange
    {'walkDown', 12},
    {'walkLeft', 8},
    {'walkDown', 4},
    {'walkRight', 7},
    {'w', 60},
    {'a', 14},
    {'w', 90},
    {'a', 16},
    {'w', 120},
    {'b', 19},
    {'w', 180}, -- we're on the water
    {'s', 10}, -- use a repel
    {'w', 296},
    {'a', 17},
    {'w', 289},
    {'walkLeft', 1},
    {'w', 247},
    {'a', 19},
    {'w', 34},
    {'a', 17},
    {'w', 153},
    {'b', 22},
    {'w', 63},
    {'b', 23},
    {'w', 70},
    {'b', 25}, -- done using repel
    {'w', 90},
    {'walkDown', 11}, -- surf to first trainer
    {'walkLeft', 12},
    {'walkDown', 2},
    {'walkRight', 3},
    {'walkDown', 2},
    {'walkRight', 14},
    {'walkDown', 3},
    {'walkRight', 2},
    {'walkDown', 3},
    {'walkDown', 2},
    {'walkLeft', 2},
    {'walkLeft', 2},
    {'walkRight', 2},
    {'walkDown', 1},
    {'walkDown', 1},
    {'w', 755},
    {'b', 7},
    {'w', 452},
    {'b', 18},
    {'w', 396},
    {'a', 15},
    {'use_move', 2}, -- defeat swimming boi 13/15 tbolt
    {'walkDown', 4},
    {'walkLeft', 3},
    {'walkDown', 4},
    {'walkLeft', 2},
    {'walkDown', 4},
    {'walkRight', 4},
    {'walkDown', 8},
    {'walkDown', 3},
    {'walkLeft', 4},
    {'walkDown', 7},
    {'walkLeft', 7},
    {'walkUp', 3},
    {'walkLeft', 4},
    {'walkDown', 2},
    {'walkLeft', 5},
    {'w', 90},
    {'b', 16}, -- reuse repel
    {'w', 309},
    {'s', 11},
    {'w', 98},
    {'a', 19},
    {'w', 111},
    {'a', 19},
    {'w', 42},
    {'a', 16},
    {'w', 175},
    {'b', 34},
    {'w', 58},
    {'b', 22},
    {'w', 78},
    {'b', 22}, -- done using repel
    {'w', 30},
    --mapChange
    {'walkLeft', 12},
    {'walkDown', 3},
    {'walkLeft', 4},
    {'walkUp', 3},
    {'walkLeft', 5},
    {'w', 700}, -- wait for swimmer to get to us
    {'b', 18},
    {'w', 441},
    {'a', 16},
    {'w', 401},
    {'a', 15}, -- battle
    {'use_move', 4}, -- tbolt 9/15
    {'walkLeft', 6},
    {'walkUp', 3},
    {'walkLeft', 4},
    {'walkDown', 4},
    {'walkLeft', 6},
    {'walkLeft', 2},
    {'walkUp', 5},
    {'walkLeft', 3},
    {'walkUp', 1},
    {'walkUp', 1},
    {'walkLeft', 4},
    {'walkLeft', 1},
    {'walkUp', 2},
    {'walkLeft', 5},
    {'walkUp', 2},
    {'walkLeft', 3},
    {'walkUp', 2},
    {'walkLeft', 2}, -- land on seafoam islands
    {'w', 90},
    {'walkUp', 3},
    {'walkLeft', 2},
    {'walkUp', 2},
    {'walkLeft', 11},
    {'walkDown', 6},
    {'walkLeft', 7},
    {'walkUp', 4},
    --mapChange
    {'w', 540}, -- enter seafoam cave
    --seafoam-1
    {'walkUp', 3},
    {'walkRight', 9}, -- repel runs out
    {'w', 90},
    {'b', 20},
    {'w', 90},
    {'s', 14}, -- use a new repel
    {'w', 90},
    {'a', 20},
    {'w', 90},
    {'a', 13},
    {'w', 30},
    {'a', 16},
    {'press_b', 5}, -- done using repel
    {'walkRight', 6}, -- go to push boulder 
    {'walkUp', 7},
    {'walkRight', 2},
    {'walkDown', 2},
    {'walkRight', 2},
    {'walkUp', 1},
    {'w', 90},
    {'a', 14},
    {'w', 130},
    {'a', 20},
    {'w', 121},
    {'a', 16},
    {'w', 246},
    {'b', 20},
    {'w', 86},
    {'b', 21},
    {'w', 87},
    {'walkUp', 1},
    {'w', 107},
    {'walkUp', 2},
    {'w', 97},
    {'walkUp', 2},
    {'w', 107},
    {'walkUp', 2},
    {'w', 161},
    {'walkRight', 2},
    {'w', 60},
    {'walkUp', 3},
    {'w', 92},
    {'walkLeft', 2}, -- boulder 1 goes down hole
    {'w', 90},
    {'walkDown', 4},
    {'walkLeft', 8},
    {'walkDown', 5},
    {'walkLeft', 8},
    {'walkUp', 9},
    {'walkRight', 4},
    {'walkUp', 2},
    {'walkRight', 7},
    {'walkUp', 2},
    {'walkRight', 9},
    {'walkDown', 5},
    {'walkRight', 6},
    {'walkDown', 3},
    {'walkRight', 3},
    {'walkUp', 3},
    {'walkLeft', 2},
    {'w', 140},
    {'walkLeft', 2},
    {'w', 78},
    {'walkDown', 2},
    {'w', 31},
    {'walkLeft', 3},
    {'w', 42},
    {'walkUp', 2}, -- boulder 2 goes down hole
    {'w', 60},
    {'walkLeft', 4},
    {'walkUp', 2},
    {'w', 47},
    {'walkLeft', 2},
    {'walkUp', 5},
    {'w', 27},
    {'walkLeft', 4}, -- repel runs out
    {'w', 72},
    {'b', 20},
    {'w', 170},
    {'s', 12}, -- use new repel
    {'w', 91},
    {'a', 18},
    {'w', 81},
    {'a', 19},
    {'w', 31},
    {'a', 21},
    {'w', 105},
    {'b', 29},
    {'w', 45},
    {'b', 26},
    {'w', 57},
    {'b', 31}, -- done with repel
    {'w', 60},
    {'walkLeft', 13},
    {'walkDown', 2},
    --mapChange
    {'w', 180},
    {'walkLeft', 3},
    {'walkDown', 12},
    {'walkRight', 6},
    {'walkUp', 8},
    {'walkRight', 4},
    {'walkUp', 7},
    {'walkRight', 7},
    {'walkDown', 4},
    {'walkLeft', 2},
    {'walkDown', 2},
    {'walkRight', 1}, -- approach boulder
    {'w', 60},
    {'a', 14}, -- use strength
    {'w', 79},
    {'a', 19},
    {'w', 127},
    {'a', 16},
    {'w', 220},
    {'b', 19},
    {'w', 51},
    {'b', 20}, -- exit prompt
    {'walkRight', 1}, -- push boulder down hole
    {'w', 70}, 
    {'walkUp', 3},
    {'walkRight', 2},
    {'walkUp', 4},
    {'walkLeft', 8},
    {'walkDown', 13},
    {'walkLeft', 2},
    {'walkDown', 3},
    {'walkLeft', 12},
    {'walkUp', 5}, -- repel runs out
    {'w', 60},
    {'b', 17},
    {'w', 60},
    {'s', 15}, -- use new repel
    {'w', 90},
    {'a', 16},
    {'w', 90},
    {'a', 16},
    {'w', 34},
    {'a', 14},
    {'w', 90},
    {'press_b', 6}, -- done using new repel
    {'w', 30},
    {'walkUp', 11},
    {'walkRight', 5}, -- down ladder
    --mapChange
    {'w', 180},
    {'walkRight', 14},
    {'walkDown', 5},
    {'walkRight', 1}, -- approach boulder
    {'w', 60}, 
    {'a', 14}, -- use strength
    {'w', 90},
    {'a', 20},
    {'w', 90},
    {'a', 15},
    {'w', 200},
    {'b', 16},
    {'w', 70},
    {'b', 19},
    {'w', 30},
    {'walkRight', 1},
    {'w', 70},
    {'walkRight', 2}, 
    {'w', 120}, -- rock goes into hole
    {'walkUp', 4},
    {'walkLeft', 16},
    {'walkUp', 2},
    --mapChange
    {'w', 180},
    {'walkLeft', 4},
    {'walkDown', 10},
    {'walkRight', 5},
    {'walkUp', 7},
    {'walkRight', 3},
    --mapChange
    {'w', 180},
    {'walkUp', 2},
    {'walkRight', 17},
    {'walkDown', 5},
    {'walkRight', 6}, -- repel wears off
    {'w', 90},
    {'b', 22},
    {'w', 165},
    {'s', 15}, -- use a new repel
    {'w', 93},
    {'a', 17},
    {'w', 108},
    {'a', 24},
    {'w', 30},
    {'a', 17},
    {'press_b', 6},
    {'walkUp', 6},
    --mapChange
    {'w', 180},
    {'walkDown', 5},
    {'walkLeft', 1}, -- face boulder
    {'w', 30},
    {'a', 14}, -- use strength
    {'w', 78},
    {'a', 23},
    {'w', 65},
    {'a', 16},
    {'w', 195},
    {'a', 23},
    {'w', 67},
    {'b', 34},
    {'walkLeft', 1},
    {'w', 70},
    {'walkLeft', 2},
    {'w', 120}, -- boulder goes down hole
    {'walkLeft', 2}, -- you go down hole
    {'w', 260},
    {'walkDown', 1},
    {'walkRight', 3},
    {'walkUp', 2},
    {'walkLeft', 1},
    {'w', 72},
    {'a', 14}, -- USE STRENGTH
    {'w', 147},
    {'b', 20},
    {'w', 94},
    {'a', 25},
    {'w', 206},
    {'a', 24},
    {'w', 64},
    {'a', 20}, -- down using strength
    {'w', 60},
    {'walkLeft', 1},
    {'w', 70},
    {'walkLeft', 2},
    {'w', 70},
    {'walkLeft', 2}, -- boulder goes down hole
    {'w', 180},
    {'walkLeft', 2}, -- you go down hole
    {'w', 260},
    {'walkDown', 4},
    {'walkLeft', 5},
    {'walkUp', 4},
    {'w', 60}, -- hop onto ground
    {'walkUp', 1},
    {'walkLeft', 5},
    {'walkDown', 6},
    {'walkRight', 6},
    {'walkDown', 5},
    {'walkLeft', 8},
    {'walkDown', 2},
    {'walkLeft', 3},
    {'walkUp', 3},
    {'walkRight', 2},
    {'walkUp', 1}, -- look at boulder
    {'w', 30},
    {'a', 20}, -- use strength
    {'w', 74},
    {'a', 32},
    {'w', 69},
    {'a', 25},
    {'w', 192},
    {'b', 26},
    {'w', 56},
    {'b', 26}, -- done using strength
    {'w', 60},
    {'walkUp', 1},
    {'w', 70},
    {'walkUp', 2},
    {'w', 70},
    {'walkUp', 1},
    {'walkLeft', 2},
    {'walkDown', 2},
    {'w', 70},
    {'walkRight', 2},
    {'walkDown', 3},
    {'walkLeft', 2}, -- push boulder
    {'w', 70},
    {'walkLeft', 1},
    {'walkDown', 2},
    {'walkLeft', 3},
    {'walkUp', 3},
    {'walkLeft', 2},
    {'w', 70},
    {'walkLeft', 2},
    {'w', 70},
    {'walkLeft', 2},
    {'w', 70},
    {'walkLeft', 2},
    {'w', 70},
    {'walkLeft', 1},
    {'walkDown', 2}, -- kick boulder down hole
    {'w', 180},
    {'walkRight', 5},
    {'walkDown', 3},
    {'walkRight', 3},
    {'walkUp', 2},
    {'walkLeft', 2},
    {'w', 70},
    {'walkLeft', 2},
    {'w', 70},
    {'walkLeft', 1},
    {'walkUp', 2},
    {'walkLeft', 2},
    {'walkDown', 2}, -- push boulder down hole
    {'w', 180},
    {'walkDown', 2}, -- you down hole
    {'w', 260}, -- land in water
    {'walkUp', 12}, -- repel wears off
    {'w', 77},
    {'b', 24},
    {'w', 146},
    {'s', 12}, -- use new repel
    {'w', 88},
    {'a', 15},
    {'w', 92},
    {'a', 25},
    {'w', 26},
    {'a', 20},
    {'w', 142},
    {'b', 22},
    {'w', 50},
    {'b', 22},
    {'w', 57},
    {'b', 24}, -- done with repel
    {'walkUp', 1},
    {'walkRight', 3},
    {'walkUp', 2},
    {'w', 90},
    {'walkUp', 2},
    {'walkLeft', 2}, -- face articuno
    {'w', 60},
    {'a', 14}, -- fight articuno
    {'w', 138},
    {'b', 18},
    {'w', 409},
    {'a', 18},
    {'w', 500}, -- await battle screen
    {'r', 15},
    {'a', 15},
    {'w', 90},
    {'walkRight', 2},
    {'walkDown', 1},
    {'a', 15},
    {'a', 15}, -- use masterball
    {'w', 900},
    {'b', 16},
    {'w', 90},
    {'b', 17},
    {'w', 120},
    {'a', 22},
    {'w', 223},
    {'a', 14}, -- name articuno
    {'w', 90},
    {'walkRight',1},
    {'a',5},
    {'walkDown',2},
    {'walkRight',1},
    {'a',5},
    {'walkLeft',2},
    {'a',5},
    {'walkUp',2},
    {'walkRight',1},
    {'a',5},
    {'walkRight',2},
    {'walkDown',1},
    {'a',5},
    {'walkLeft',3},
    {'walkUp',1},
    {'a',5},
    {'walkDown',3},
	{'walkRight',5},
    {'a',5},
    {'s', 15},
    {'a', 15},
    {'w', 180}, -- bombjay named
    {'w', 60},
    {'walkDown', 3},
    {'w', 60},
    {'a', 16}, -- try surfing
    {'w', 113},
    {'a', 19},
    {'w', 113},
    {'b', 20},
    {'w', 240}, -- we on the water
    {'walkLeft', 2},
    {'walkDown', 11},
    {'walkRight', 5},
    {'walkUp', 5}, -- hop onto land
    {'w', 90},
    {'walkUp', 3},
    {'walkRight', 3}, -- up the ladder
    --mapChange
    {'w', 180},
    {'walkLeft', 2},
    {'walkUp', 6},
    {'walkLeft', 5},
    {'walkDown', 9},
    {'walkRight', 11},
    {'walkUp', 5},
    {'walkRight', 5},
    {'walkDown', 3},
    {'w', 90},
    {'a', 18},
    {'w', 94},
    {'a', 22}, -- surf
    {'w', 53},
    {'a', 20},
    {'w', 387},
    {'walkRight', 4},
    {'w', 53},
    {'walkDown', 2},
    {'w', 56},
    {'walkRight', 4},
    {'w', 60},
    {'walkUp', 2},
    {'w', 90}, -- hop onto land
    {'walkUp', 1},
    {'walkRight', 4},
    {'walkDown', 5},
    {'walkLeft', 2},
    {'walkDown', 3},
    {'walkRight', 3}, -- up ladder
    --mapChange
    {'w', 180},
    {'walkRight', 1},
    {'walkUp', 4}, -- up ladder
    --mapChange
    {'w', 180},
    {'walkDown', 6},
    {'walkLeft', 5}, -- up ladder
    --mapChange
    {'w', 180},
    {'walkRight', 4}, -- repel runs out
    {'w', 90},
    {'b', 17},
    {'w', 90},
    {'s', 18}, -- new repel
    {'w', 123},
    {'a', 16},
    {'w', 90},
    {'walkLeft', 2},
    {'w', 20},
    {'a', 15},
    {'a', 15},
    {'press_b', 6},
    {'walkRight', 1},
    {'walkDown', 4}, -- out of caves
    {'w', 540},
}
