cave = {
	{'w',1},
	{'walkRight', 9}, -- walk out of verm
    --mapChange
    {'walkUp', 21},
    {'walkRight', 7},
    {'walkUp', 9},
    {'walkLeft', 10},
    {'walkUp', 8},
    {'walkRight', 9},
    {'walkDown', 3},
    {'walkRight', 4},
    {'walkUp', 3},
    --mapChange
    {'w', 150},
    {'walkUp', 2},
    {'w', 36},
    {'walkRight', 3},
    {'w', 27},
    {'walkUp', 3},
    {'w', 31},
    {'walkLeft', 3},
    --mapChange
    {'w', 150},
    {'walkUp', 58},
    {'w', 80},
    --mapChange
    {'walkRight', 3},
    {'w', 108},
    {'walkDown', 5},
    {'walkLeft', 2},
    {'walkDown', 1},
    --mapChange
    {'w', 205},
    {'walkLeft', 4},
    {'w', 30},
    {'walkUp', 5},
    {'w', 29},
    {'walkRight', 3},
    {'w', 36},
    --mapChange
    {'walkUp', 36},
    {'w', 41},
    {'walkRight', 11},
    {'w', 29},
    {'walkUp', 16},
    {'w', 39},
    --mapChange
    {'walkRight', 10},
    {'w', 32},
    {'walkUp', 2},
    {'w', 38},
    {'walkRight', 2},
    {'w', 128},
    {'a', 20},
    {'w', 57},
    {'a', 21},
    {'w', 66},
    {'a', 20},
    {'w', 69},
    {'a', 22},
    {'w', 433},
    {'walkRight', 12}, -- prep first trainer fight
    {'walkDown', 3},
	{'w', 300},
	{'a', 30},
	{'w', 300},
	{'a', 30},
	{'w', 150},
	{'a', 30},
	{'w', 400}, -- enter battle with alicia
	{'use_move', 4}, -- kill oddish, bellsprout, oddish, bellsprout
	{'press_b', 6}, -- exit the battle to overworld
	{'w', 100},
	{'walkDown', 6},
	{'walkRight', 6},
	{'w', 70},
	{'walkRight', 2},
	{'walkDown', 1},
	{'a', 20},
	{'w', 88},
	{'a', 28},
	{'w', 50},
	{'a', 24},
	{'w', 480},
	{'a', 25},
	{'w', 300}, -- fight rock trainer
	{'use_move', 1}, -- kill machop
	{'a', 15},
	{'r', 15}, -- switch to flamethrower for onix
	{'use_move', 1}, -- kill onix
	{'press_b', 6}, -- beat rock trainer
	{'w', 150},
	{'walkDown', 1}, -- move to bug trainer
	{'w', 30},
	{'walkUp', 4},
	{'walkRight', 15},
	{'walkRight', 18},
	{'walkUp', 7},
	{'w', 400}, -- fight bug trainer
	{'a', 22},
	{'w', 600},
	{'a', 17},
	{'w', 480},
	{'use_move', 3}, -- destroy him
	{'press_b', 4},
    {'walkUp', 3},  -- move to next rock trainer
    {'w', 15},
    {'walkLeft', 3},
    {'walkUp', 3},
    {'walkLeft', 3},
    {'walkUp', 2},
    {'walkRight', 90},  -- intercept him at a random point
    {'w', 80},
    {'a', 15},
    {'a', 15},
    {'a', 15},
    {'a', 15},
    {'w',300},
    {'a',15},
    {'w',240},
    {'a',60},
    {'w',240},
    {'a', 15},
    {'r', 15},
    {'use_move', 3},
    {'press_b', 4},
    {'walkLeft', 15},
    {'w', 30},
    {'walkUp', 2},
    {'walkRight', 16},
    {'walkDown', 1},
    {'a', 60},
    {'press_b', 4},
    {'walkRight', 2},
    {'walkDown', 9}, -- fight picknicker girl
    {'w',300},
    {'a',15},
    {'w',240},
    {'a',60},
    {'w',240},
    {'a',60},
    {'w',400},
    {'use_move', 1},
    {'press_b', 4},
    {'walkRight', 14}, -- move to rock cave pokecenter
    {'walkDown', 5},
    {'walkRight', 13},
    {'walkDown', 13},
    {'walkLeft', 5},
    {'walkUp', 7},
    --mapChange
    {'w', 150}, -- enter pokecenter and heal
    {'walkUp', 7},
    {'pokecenter_heal', 1},
    -- breakpoint
    {'walkDown', 6}, -- out of pokecenter
    --mapChange
    {'w', 200},
    {'walkDown', 7},
    {'walkLeft', 5},
    {'w', 200},
    {'b', 17},
    {'w', 74},
    {'b', 20},
    {'w', 600},
    {'b', 13},
    {'w', 400},
    {'a', 60},
    {'r',15},
    {'use_move', 2}, -- defeat picknicker
    {'press_b', 5},
    {'w', 261},
    {'walkLeft', 7},
    {'w', 23},
    {'walkUp', 9},
    {'w', 49},
    {'walkRight', 7},
    {'w', 63},
    {'walkUp', 2},
    --mapChange
    {'w', 653},
    {'s', 15},
    {'w', 194},
    {'a', 18},
    {'w', 256},
    {'walkLeft', 5},
    {'w', 30},
    {'w', 200},
    {'walkDown', 5},
    {'walkUp', 2},
    {'w', 30},
    {'a', 20},
    {'w', 35},
    {'a', 21},
    {'w', 212},
    {'b', 25},
    {'w', 41},
    {'b', 18},
    {'w', 25},
    {'b', 26},
    {'w', 30},
    {'b', 30},
    {'b', 30},
    {'w', 100},
    {'walkRight', 4},  -- go to science man
    {'walkDown', 7},
    {'walkRight', 5},
    {'walkDown', 3},
    {'w', 330},
    {'a', 20},
    {'w', 400},
    {'a', 20},
    {'w', 500},
    {'a', 20},
    {'use_move', 2},  -- defeat pokemaniac
    {'press_b', 5},
    {'w', 447},
    {'walkDown', 2},
    {'w', 233},
    {'walkDown', 1},
    {'w', 398},
    {'walkRight', 22},
    {'w', 62}, -- climb  down ladder
    --mapChange
    {'walkUp', 13}, -- go to next pokemaniac
    {'w', 200},
    {'walkDown', 11},
    {'walkUp', 2},
    {'walkLeft', 10},
    {'w', 500},
    {'a', 18},
    {'w', 400},
    {'a', 20},
    {'w', 400},
    {'a', 20},
    {'use_move', 1}, -- defeat pokemaniac 
    {'press_b', 4},
    {'w', 335},
    {'walkLeft', 4}, -- move to pickniker
    {'w', 53},
    {'walkUp', 2},
    {'w', 310},
    {'walkLeft', 8},
    {'w', 262},
    {'walkLeft', 1},
    {'w', 70},
    {'walkUp', 4},
    {'w', 391},
    {'a', 18},
    {'w', 409},
    {'a', 15},
    {'w', 471}, -- start battle
    {'use_move', 2},
    {'press_b', 4}, -- finish battle
    {'w', 345},
    {'walkUp', 6}, -- move to scientist
    {'w', 222},
    {'walkRight', 6},
    {'w', 146},
    {'walkRight', 5},
    {'w', 326},
    {'walkUp', 4},
    {'w', 312},
    {'a', 16},
    {'w', 93},
    {'s', 13}, -- reapply repel
    {'w', 129},
    {'a', 18},
    {'w', 170},
    {'a', 21},
    {'w', 719},
    {'a', 21},
    {'w', 163},
    {'a', 23},
    {'w', 241},
    {'b', 23},
    {'w', 83},
    {'b', 24},
    {'w', 326}, -- end repel
    {'walkUp', 2}, -- move to scientist
    {'w', 104},
    {'w', 230},
    {'a', 27},
    {'w', 367},
    {'a', 23},
    {'w', 367},
    {'a', 26},
    {'use_move', 2},
    {'press_b', 4},
    {'w', 300},
    {'walkUp', 5}, -- move to rock trainer
    {'w', 300},
    {'walkRight', 15},
    {'w', 150},
    {'walkUp', 8},
    {'w', 263},
    {'walkLeft', 6},
    {'w', 320},
    {'a', 1},
    {'w', 415}, -- fight rock trainer
    {'a', 12},
    {'w', 445},
    {'a', 22},
    {'r', 1},
    {'use_move', 1},
    {'press_b', 4},
    {'w', 725},
    {'walkLeft', 4},
    {'w', 507},
    {'walkUp', 11},
    {'w', 116},
    {'walkDown', 2},
    {'w', 26},
    {'walkRight', 2},
    --mapChange
    {'w', 266},
    {'walkDown', 4},
    {'w', 39},
    {'walkRight', 3},
    {'w', 161},
    {'walkDown', 2},
    {'w', 26},
    {'walkRight', 2},
    {'w', 290},
    {'a', 24},
    {'w', 356},
    {'a', 26}, -- start fight with rock type trainer
    {'w', 398},
    {'a', 18},
    {'r', 15},
    {'use_move', 3}, -- flamethrower rock types
    {'a', 15},
    {'l', 15},
    {'use_move', 1}, -- wing attack machop
    {'press_b', 4}, -- finish battle
    {'w', 511},
    {'walkRight', 5}, -- move to next rock trainer
    {'w', 60},
    {'walkDown', 13},
    {'w', 60},
    {'walkRight', 9},
    {'w', 31},
    {'walkUp', 2},
    {'w', 388},
    {'a', 12},
    {'w', 360},
    {'a', 29},
    {'w', 478},
    {'a', 16},
    {'r', 15},
    {'use_move', 2},
    {'press_b', 5},
    {'w', 335},
	{'walkUp', 4}, -- move up ladder
	{'w', 38},
	{'walkRight', 2},
	--mapChange
	{'w', 300},
	{'walkLeft', 9}, -- move to picknicker
	{'w', 416},
	{'walkLeft', 4},
	{'w', 176},
	{'walkDown', 7},
	{'w', 248},
	{'walkLeft', 4},
	{'w', 314},
	{'a', 8},
	{'w', 48},
	{'s', 15}, -- reapply repel
	{'w', 77},
	{'a', 16},
	{'w', 136},
	{'a', 19},
	{'w', 47},
	{'a', 16},
	{'w', 84},
	{'a', 21},
	{'w', 77},
	{'b', 28},
	{'w', 76},
	{'b', 28}, -- end repel
	{'w', 271},
	{'walkLeft', 1},
	{'w', 208},
	{'a', 24},
	{'w', 99},
	{'a', 20},
	{'w', 423},
	{'a', 19},
	{'w', 372},
	{'use_move', 3}, -- defeat picknicker
	{'press_b', 4},
	{'w', 200},
	{'walkLeft', 3}, -- move to rock trainer
	{'w', 305},
	{'walkUp', 3},
	{'w', 60},
	{'walkUp', 3},
	{'w', 138},
	{'walkLeft', 4},
	{'w', 274},
	{'a', 17},
	{'w', 400},
	{'a', 25},
	{'w', 500},
	{'a', 18},
	{'r', 15},
	{'use_move', 3},
	{'press_b', 4},  -- defeat rock trainer with 4 flamethrower left
	{'w', 300},
	{'walkLeft', 4}, -- move to pokemaniac
	{'w', 68},
	{'walkUp', 5},
	{'w', 69},
	{'walkUp', 2},
	{'w', 60},
	{'walkUp', 1},
	{'w', 48},
	{'walkRight', 1},
	{'w', 40},
	{'a', 18},
	{'w', 120},
	{'a', 21},
	{'w', 399},
	{'a', 26},
	{'w', 377},
	{'a', 25},
	{'use_move', 3}, -- wing attack all three slowpokes
	{'press_b', 6}, -- level up to 57
	{'walkLeft', 2},
	{'w', 60},
	{'walkUp', 4},
	{'walkRight', 2},
	--mapChange
	{'w', 332}, -- go to picknicker
	{'walkLeft', 3},
	{'w', 59},
	{'walkDown', 4},
	{'w', 300},
	{'a', 16},
	{'w', 79},
	{'a', 18},
	{'w', 466}, -- fight picknicker
	{'a', 22},
	{'w', 421},
	{'a', 21},
	{'use_move', 2},
	{'press_b', 5}, -- defeat picknicker
	{'w', 100},
	{'walkDown', 4}, -- go to next pickniker 
	{'w', 439},
	{'a', 16},
	{'w', 493},
	{'a', 19},
	{'w', 536},
	{'a', 17},
	{'use_move', 4}, -- defeat them
	{'press_b', 5},
	{'w', 100}, -- go to last
	{'walkDown', 5},
	{'w', 299},
	{'walkLeft', 5},
	{'w', 66},
	{'walkDown', 2},
	{'w', 42},
	{'walkLeft', 7},
	{'w', 204},
	{'walkUp', 3},
	{'w', 26},
	{'walkLeft', 8},
	{'w', 285},
	{'a', 17},
	{'w', 424},
	{'a', 25},
	{'w', 406},
	{'a', 17},
	{'use_move', 3},
	{'press_b', 4},
	{'w', 60},
	{'walkLeft', 6},
	{'w', 30},
	{'walkDown', 6},
	{'w', 30},
	{'walkLeft', 3},
	{'w', 40},
	--mapChange
	{'walkDown', 4}, -- out of cave
	{'w', 300}, -- go to lavender town
}
